### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by kurdikeyboard**
Added kurmanci kurdish layout.

### CODE REVIEW

**Comment by patrickgold** [comment]
I've manually adjusted the preferred layouts, see above commit. Closing this PR because all changes are now in master.

**Comment by alissonlauffer** [comment]
> Closing this PR because all changes are now in master.

Tip: When a pull request is opened you gain push access to the branch where the pull request was opened, so you are able to make changes or rebase it directly.

**Comment by patrickgold** [comment]
> When a pull request is opened you gain push access to the branch where the pull request was opened, so you are able to make changes or rebase it directly.

This PR is special because parts of the changes here are already in #530 and the commit above was just an adjustment to the config because I had forgotten to add the preferred layout in the merge conflict resolving, so yeah. And for the push: it rejected the push for this branch (why I am unsure) with "Permission denied" by the remote (GitHub), so I just committed this directly to the master branch.

**Comment by kurdikeyboard** [comment]
That's great thank you so much :)

**Pull request closed without merging**
