### PR TITLE
Implement Latin NLP provider (part 2)

### LINKED ISSUE #2150: Glide Typing will suggest sexual word
I've omitted the word from the title due to its nature.

#### Short description
I have not been able to find another sexual word which will be suggested via glide type.

However, the term "cumming" will be suggested via glide type. This can rarely be achieved on accident by glide typing "coming", or easily by accident glide typing "cunning". (I have not been able to replicate for "coming", but a friend has.)

I'm pretty sure this wasn't intentional.

#### Steps to reproduce
1. Enable Glide Typing
2. Intentionally try to glide type "cumming", or lazily glide type "cunning" or "coming"
3. Achieve suggestion "cumming"

#### Environment information
- FlorisBoard Version: 0.4.0-alpha04 (90)
- Install Source: F-Droid
- Device: Pixel 6
- Android: CalyxOS 4.5.1 (Android 13)

### LINKED ISSUE #2155: Swipping text just in english
I'm using the 4.0 release. I just the spanish keyboard. And i'm getting english mixed with spanish...
I just have installed the spanish latinoamerican keyboard.

### PR DESCRIPTION
**Pull request by patrickgold**
This PR is a continuation of #2196.

Status: NLP bridge is partially implemented; resolving bugs and performance issues; trying to find solution for currently broken glide typing

Relevant PRs:
- florisboard/nlp#3
- florisboard/nlp#4
- florisboard/nlp#5
- florisboard/nlp#6

---

Closes #2150 
Closes #2155

### CODE REVIEW

**Comment by BHydden** [comment]
Feels close 🙂 odd after all this time! 😁

**Comment by patrickgold** [comment]
It's getting closer and closer each commit - but as you might see from the changes I have to account for quite a lot of stuff in the JNI bridge itself before the actual suggestions are displayed. ATM I got C++ exceptions to properly be handled (as ICU extensions and also the NLP core depend on exceptions for unexpected behavior). And I played around with some of the NlpSession bridging, which seems to work for now.

So if nothing goes wrong in the next few days there will be the first app-debug.apk artifact with suggestions working :)

**Comment by lm41** [comment]
How long I have waited for this.... Finally, the messages I write will no longer look like those of a drunk. Thanks for everything

**Comment by Rorschach1010** [comment]
I installed this apk so I finally can use Florisboard with glide and a german dictionary but somehow when I activate glide typing, it's not working at all. Am I doing something wrong? When I install the latest beta, glide typing is working.

**Comment by antaljanosbenjamin** [comment]
If you need help with the C++ part, I can try to help. I am not too familiar with C++ on android, but I am using C++ on my daily job. Feel free to ping me, if you need help.

**Comment by MartinNowak** [comment]
Do you have some sort of todo list for *this* PR with which we could help you @patrickgold?
Or maybe we could break the topic down a bit and help with a few PRs to finish this feature branch.

**Comment by patrickgold** [comment]
This PR's approach to plugins was abandoned and will be replaced by the new NLP algorithm in v0.5.

**Pull request closed without merging**
