### PR TITLE
Bengali keyboard layout

### PR DESCRIPTION
**Pull request by iamrasel**
This PR contains the Bengali keyboard layout, followed by the contribution guideline provided [here](https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md). I hope everything is okay to merge this request.

<table>
 <tr>
  <td></td>
  <td></td>
 </tr>
 <tr>
  <td></td>
  <td></td>
 </tr>
</table>

### CODE REVIEW

**Comment by kawoser** [comment]
How can I add this Bangla layout on my florisboard keyboard ? Please reply

**Comment by iamrasel** [comment]
@kawoser you'll need to build the app with the changes I had made.

**Comment by kawoser** [comment]
@iamrasel how can i build up ? Have you already build up this layout on app ? Please provide me this florisboard apk link...
http://kawosershuvo@gmail.com

**Comment by kawoser** [comment]
@iamrasel  thank you very much 😊 I've received your mail. Now I can write in Bangla on Florisboard.
Thank you dude

**Comment by kawoser** [comment]
@iamrasel ,
After typing via Bangla layout which you have made, I would like to give you some suggestion.
Mention that, I never know debugging or building such layout.

1. There should "Dari" ( । ) on Bangla layout.
2. There should "zwnj key" , because র‍্যাম, র‍্যালী can't be typed through this layout.
3. If possible, you can add "phonetic bangla" layout like as "অভ্র" .

After all this is great to have bangla layout. Thank you

**Comment by iamrasel** [comment]
@kawoser The Bengali punctuation symbol Dari (।) can be obtained by long pressing the full stop (.) button. I know it's kind of inconvenient, but that's all I could do.

And the letter `্য` only causes issue with the letter `র`. FlorisBoard's way of handing combined/joint letters is different compared to other keyboards. Though it works fine with other combined letters, but I don't know the problem with creating the letter `র‍্য`.

About Avro (Bengali Phonetic) layout - I don't know how to implement this, sorry. To get phonetic experience with open source, you can try [Indic Keyboard](https://f-droid.org/packages/org.smc.inputmethod.indic), i've been also using it for this reason.

I had also contributed Bengali Bijoy layout to these two lightweight open source keyboard, they have no problem with writing `র‍্য`.

* [Simple Keyboard](https://f-droid.org/packages/rkr.simplekeyboard.inputmethod)
* [Unexpected Keyboard](https://f-droid.org/packages/juloo.keyboard2)

**Comment by iamrasel** [comment]
@GoRaN909 Can you please show me where did I do that? File name along with the line number would be helpful. I see no such mistake from my end.

**Comment by kawoser** [comment]
@iamrasel  Thank you so much for your details reply. I've tried both of keyboard, they are amazing. It is a great experience.

**Review by patrickgold — CHANGES_REQUESTED** [review]
Hey iamrasel,

first of all I want to apologize for not reviewing your PR for so long, I have been pretty occupied the last few months and my life was pretty stressful, which led to me not having much time for FlorisBoard. Hope you can understand!

Second, I have reviewed your changes and tested out your layout. As far as I can tell your layout is implemented really well and you have also written the config really clean, well done!

The only small thing which is incorrect are the TLDs Goran mentioned, I've attached a review comment to the relevant section. Once that is fixed I will merge in your changes and they will be released with the next alpha release :)

**Comment by iamrasel** [comment]
@patrickgold Thank you for the review. I just committed with the necessary changes you asked for, and this commit also contains the fix for the letter `র‍্য` as @kawoser mentioned earlier.

**Review by patrickgold — APPROVED** [review]
Thanks a lot for the changes, now everything checks out. Merging in your changes, thanks again for your PR!

**Comment by Tarek-Hasan** [comment]
Very much thanks for your contribution, @iamrasel.
If you want to improve bangla typing experience, you can look in #1885. In there, I listed Bangla keyboard and word-list/dictionary resources. Hope it helps.

**Comment by Tarek-Hasan** [comment]
@iamrasel, if you don't mind.
Will you be able to add Bangla support to [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard), please?

**Comment by mehedi2580** [comment]
@patrickgold sir , why you close this proposal ? still this keyboard dont have google bangla layout.

**Comment by patrickgold** [comment]
This is a merged in PR... The issue I closed was a duplicate

**Pull request merged**
