### PR TITLE
fix: add check for null selectedText when performing a copy

### LINKED ISSUE #1232: copying selected text (crash)
#### Short description
i was trying to copy text using app and i tapped hardly on selected text. if this reoccurs again, i will provide more detail steps.
browser: mull 91.2.0

#### Steps to reproduce
1. Go to https://www.wikidata.org/wiki/Q5496658
2. Click on label
3. select text
4. try to tap copy icon on keyboard
5. See crash

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-J701F
- Android: 9 (cn=P sdk=28)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1630942631938.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:882)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCopy(EditorInstance.kt:577)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:893)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```
</details>

### LINKED ISSUE #1468: Restarted while just typing
#### Short description
FlorisBoard unexpectedly restarted while just typing.

#### Steps to reproduce
Unknown

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Xiaomi MI 8
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1640279767066.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:882)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCopy(EditorInstance.kt:577)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:893)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>

### LINKED ISSUE #1554: Copy to clipboard crash
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

#### Environment information
- FlorisBoard Version: 0.3.14-beta10 (66)
- Device: Xiaomi Redmi Note 9 Pro
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1644296550795.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:947)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCopy(EditorInstance.kt:644)
	at dev.patrickgold.florisboard.ime.keyboard.KeyboardManager.onInputKeyUp(KeyboardManager.kt:590)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```
</details>

### LINKED ISSUE #1576: Tapping copy icon twice crashed the keyboard
#### Short description
I accidentally tapped on copy button on Florisboard and it crashed.

#### Steps to reproduce
Couldn't replicate it.

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-A307FN
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1644911207200.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at dev.patrickgold.florisboard.ime.core.EditorInstance$Region.getIcText(EditorInstance.kt:882)
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardCopy(EditorInstance.kt:577)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:893)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$5.invokeSuspend(InputEventDispatcher.kt:136)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>

### PR DESCRIPTION
**Pull request by Thumbscrew**
Fix #1232 
Fix #1468 
Fix #1554 
Fix #1576 

Added an additional check for `ic.getSelectedText(0)` being `null`

### CODE REVIEW

**Comment by patrickgold** [comment]
Thanks for your PR!

Just checked your changes and updated the issues this PR fixes. This change will prevent this crash, but it may introduce instances where the copy button now does nothing. Time and testing will tell if this is actually the case, will merge your fix now in though.

**Comment by Glitchy-Tozier** [comment]
> This change will prevent this crash, but it may introduce instances where the copy button now does nothing.

It might be a good idea to display a toast in those cases, which says something like "no text selected".

**Comment by Thumbscrew** [comment]
It returns an empty string `""` which I believe does get added to the clipboard. This is a bit of a crude fix so maybe it would be better to ignore the selected text when it's an empty string? When I get a chance I'll do some digging and see if I can find a better way.

**Comment by patrickgold** [comment]
@Thumbscrew PR #1653 now contains a fix which displays a toast message instead of adding an empty item. For some instances (like holding cut and copy at once) this toast is the correct way to solve the problem, but for some other instances where a simple copy fails we need to dig deeper where exactly the issue occurs.

**Pull request merged**
