### PR TITLE
Added a button for switching to an IME that supports voice

### PR DESCRIPTION
**Pull request by ElishaAz**
https://github.com/florisboard/florisboard/issues/195
Add a button for switching to an IME that supports voice.

You'll need to install a keyboard that has the voice input mode. [I built one using Vosk](https://github.com/ElishaAz/Vosk-Voice-IME/releases/tag/v1.0.0). Other options are [Google Speech Services](https://play.google.com/store/apps/details?id=com.google.android.tts), and [Konele](https://github.com/Kaljurand/K6nele/).

### CODE REVIEW

**Comment by patrickgold** [comment]
I tested out your changes and also tried out quite a lot, sadly I was not able to get the code inside switchToVoiceInputMethod() to work at all (a voice IME was installed and AnySoftKeyboard used it correctly.

The problem is that I need to build a service bridge to work with [Android Speech Recognition](https://developer.android.com/reference/android/speech/package-summary), which is considerably more work that I expected (because the speech overlay is a transparent activity, but the keyboard is a service). For now I will leave this PR open, if you want to experiment with it you can, else I will have to in a later stage.

**Comment by ElishaAz** [comment]
It works for me:
Switch to voice IME gif
 
Was the voice IME enabled in the settings?
I'm using Android 12. I'll try running it on other versions.

Anyways, 
I created a new branch that uses Android Speech Recognition: [https://github.com/ElishaAz/florisboard/tree/integrated-voice-input]().The speech overlay is not required.
It needs the `RECORD_AUDIO` permission, and a voice input method must be chosen as default in Settings->Apps->Default Apps->Digital assistant app->Voice input.
It works with `Speech Services by Google`, and `Kolene (fast recognition)`. I didn't manage to get it to work with [Vosk Recognizer](https://github.com/ewheelerinc/LocalSTT/) (permission error. Might be specific to Android 12).
This will probably need a lot more work to integrate it into the keyboard.

**Comment by patrickgold** [comment]
Hmm I just noticed my device per se does not have a voice IME but a system speech recognizer (Google in my case). Still the keyboards used this system speech recognizer without a hassle, a primary example is AnySoftKeyboard (open-source) and Microsoft SwiftKey. Gboard (with the LatinIME package name) does have a voice IME integrated but does not expose it to third-party apps on my device (no subtypes with "voice"-type exposed). OpenBoard does sometimes show the button, and if it does it also brings up the voice overlay.

I just dug further into SpeechRecognizer and you indeed need the RECORD_AUDIO permission, but this is something I don't want to add, specifically because other keyboards achieved the same without said permission (and FlorisBoard at least atm is not a voice IME).

So it seems like adding this button is much more complicated than anticipated. For the next beta release tomorrow I don't have the time to figure out an idea, but afterwards I may look into it (or you do, but please tell me first so we don't work on the same thing).

**Comment by adeyo50** [comment]
i installed a couple of the apps previously listed and was able to do this (see short video). I selected the u.s. language pack of Google found within the konele app settings. Also, performed an internet search using the konele app. Best thing I found is that both speech recognition apps work flawlessly in airplane mode and offline. Is it possible to integrate one of these into the keyboard with a mic button? https://u.pcloud.link/publink/show?code=XZyo8VVZDkYjC091nHBV56Ba95e8PFHCh8Sy

https://u.pcloud.link/publink/show?code=XZQyQVVZjAf2bTN5b4QGbU8PiXU1fubqhxPV

**Comment by adeyo50** [comment]
@ElishaAz
I can't code or "build" an app, so I can't test out your fork. Do you have your additions (ie the florisboard shown in your video above with clickable microphone button) in an apk that I could have to try? I've managed to get speech recognition working on my phone and set as default using other people's hacks and want to see whether florisboard will work or it will still use Google.

**Comment by adeyo50** [comment]
> It works for me: Switch to voice IME gif
> 
Is it possible to get an apk of this version to play around with? I have a note 20 degoogled and pixel with graphene... Also, obviously degoogled. I'd like to see if it plays nicely with any of the STT, speech recognition etc that I've installed as alternatives. I don't know how to build an apk yet
>

**Comment by ElishaAz** [comment]
Here is a build of this fork: https://github.com/ElishaAz/florisboard/releases/download/v0.3.15-debug-voice/app-debug.apk

**Comment by ElishaAz** [comment]
> Hmm I just noticed my device per se does not have a voice IME but a system speech recognizer (Google in my case). Still the keyboards used this system speech recognizer without a hassle, a primary example is AnySoftKeyboard (open-source) and Microsoft SwiftKey. Gboard (with the LatinIME package name) does have a voice IME integrated but does not expose it to third-party apps on my device (no subtypes with "voice"-type exposed). OpenBoard does sometimes show the button, and if it does it also brings up the voice overlay.
> 
> I just dug further into SpeechRecognizer and you indeed need the RECORD_AUDIO permission, but this is something I don't want to add, specifically because other keyboards achieved the same without said permission (and FlorisBoard at least atm is not a voice IME).
> 
> So it seems like adding this button is much more complicated than anticipated. For the next beta release tomorrow I don't have the time to figure out an idea, but afterwards I may look into it (or you do, but please tell me first so we don't work on the same thing).

It seems that AnySoftKeyboard create an invisible activity that calls the voice overlay and then returns the result using `ServiceConnection`.

Related code: https://github.com/AnySoftKeyboard/AnySoftKeyboard/tree/main/ime/voiceime/src/main/java/com/google/android/voiceime

Personally I would prefer switching to a voice IME over the voice overlay, but perhaps we can make it an option in settings.

**Comment by ElishaAz** [comment]
I'd like to finish with this.
Can you tell me what needs to be changed so you'll merge this pull request?

**Comment by patrickgold** [comment]
@ElishaAz I need to test this again with the voice IMEs you provided and evaluate based off that, if we can add this in the current state. Will do that in the next days before releasing the next 0.3.16 beta release.

**Comment by patrickgold** [comment]
Ok so I reviewed this PR again and if you have a proper voice IME installed, your implementation actually works fine!

I just changed the voice key position within the Smartbar to be before the one-handed toggle, so on smaller devices it does not get hidden. I also added a toast if no voice IME can be found, so the user always has feedback on his press, either the voice IME popping up or the failure toast showing.

So from that point of view, I think I will merge your changes in, as this is a good improvement. However there's still the problem that many newer devices do not come preinstalled with a proper voice IME anymore (e.g. Gboard is preinstalled but it does not expose its voice capabilities to other IMEs). So in the future we will need to see if an implementation of the voice overlay feature (as a fallback) may be viable.

**Pull request merged**
