### PR TITLE
Fix typo in strings.xml

### PR DESCRIPTION
**Pull request by Spiryt7**
Found a small typo in strings.xml

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
Honestly, both seem fine to me. "Should" sounds somewhat elegant 🤔

**Comment by zeGolem** [comment]
> Honestly, both seem fine to me. "Should" sounds somewhat elegant thinking

Main issue I can see is that this kind of wording may confuse non-native English speakers, because it's not the "conventional" use of "should"

**Comment by Glitchy-Tozier** [comment]
I see what you mean. However, in my opinion, we can expect people that don't have sufficient knowledge of the English language to have Android set to a language they properly understand.

That being said, let's see what Patrick thinks, once he gets around to looking at this PR. :)

**Comment by patrickgold** [comment]
For me as a non-native English person deciding what is better in this particular instance is extremely difficult. I tried looking this up on the internet and grammatically both are correct, only that "if" is less formal than "should".

But I think going for "if" is the better option here, because it reads a bit better and more fluent (and it is also shorter so better for smaller device screens). Will merge this change in after #1440 is merged, so it will be part of beta08.

**Pull request merged**
