### PR TITLE
Qw123wh description play store italian

### PR DESCRIPTION
**Pull request by qw123wh**
check if there are any problems. Maybe the accented letters give problems I don't know

### CODE REVIEW

**Comment by qw123wh** [comment]
the second file is the important one (add file via upload) . The former is useless

**Comment by patrickgold** [comment]
Thank you for your submission. The accented letters indeed are only a question mark (= invalid character code). Did you use UTF-8 as the file encoding in your text editor? If that doesn't work you can also use HTML entities (see [https://www.freeformatter.com/html-entities.html](https://www.freeformatter.com/html-entities.html) section ISO-8859-1 Characters).
For instance: `abcdéf` would be written as `abcd&eacute;f`. The PlayStore then correctly renders the letter with its accent.

**Comment by qw123wh** [comment]
I changed the accented letters see if that's okay.  However, it would be much easier for me to send you the translated files via email.

**Comment by patrickgold** [comment]
Thank you for your submission, this time everything is ok.

Regarding sending the translation files via E-Mail: I intend to keep all changes on GitHub and manage them via pull requests, but I can do an exception for you in the future, if it is easier for you this way.

**Comment by qw123wh** [comment]
OK thanks.  We will talk about this later when there is more to translate

**Pull request merged**
