### PR TITLE
Add Bulgarian layouts

### LINKED ISSUE #235: Bulgarian keyboard layout
Hi,
Just encountered this project and kudos to what you've done here.
My suggestion is to add a bulgarian keyboard layout. It's cyrillic. 
Here is a screenshot of the Phonetic layout
Screenshot_20210125-000222

Thanks in advance.

### PR DESCRIPTION
**Pull request by Iorvethe**
Hi! This PR should close #235. I hope it's alright.

### CODE REVIEW

**Comment by Iorvethe** [comment]
I'll also try to add the regular Bulgarian layout (and popups) one of these days.

**Comment by patrickgold** [comment]
Thanks for the PR, I really appreciate it! I am always happy if others contribute layouts, so it is more than alright :)

I've had a quick look over your changes and they look clean to me. One question: Is it intended that the Bulgarian layout does not have extended popups?

If the popup question can be resolved, I will happily merge your changes!

**Comment by Iorvethe** [comment]
Oof, I just noticed I commited with my student account... Don't mind it, I'm the same person!

As for the popups, there they are.

**Comment by patrickgold** [comment]
Thanks for adding the extended popups! I've tested your changes locally and everything checks out. Merging into master now.

**Comment by Iorvethe** [comment]
Great! Thanks for everything you do on this project :)

**Pull request merged**
