### PR TITLE
Added Estonian layout

### LINKED ISSUE #2072: Estonian layout
Hi everybody, and thank you all for your hard work. I've been using this keyboard for some time (turkish-Q) and I would like to have an estonian layout like the screenshot. GBoard has an estonian layout and it would be very cool if florisboard has an estonian layout as well, so that I could practice estonian better when i am typing (:

eest

### PR DESCRIPTION
**Pull request by OneSheepy**
This PR contains the addition of Estonian layout. It is mostly the same as "Swedish/Finnish" one, but with a few keys modified/added.

Closes #2072

### CODE REVIEW

**Comment by tsiflimagas** [comment]
Thanks for your contribution! Could you also add that your PR fixes #2072? This way that issue will be automatically closed when it gets merged.

**Comment by BHydden** [comment]
> Could you also add that your PR fixes #2072?

It's too late unfortunately. GitHub doesn't see it in comments or edits. It needs to be included in the commit message.

**Comment by tsiflimagas** [comment]
Really? I don't remember something very specifically, but I think I remember a few cases where it was asked to edit the PR description to add the issue number and it worked when the merge was done.

**Comment by OneSheepy** [comment]
I added "(#2072)" to the end of my PR message, I hope that it helps.

**Comment by BHydden** [comment]
"You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message. "
 https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#:~:text=You%20can%20link%20a%20pull%20request%20to%20an%20issue%20by%20using%20a%20supported%20keyword%20in%20the%20pull%20request%27s%20description%20or%20in%20a%20commit%20message.

No mention of comments or edits 🤷‍♂️

**Comment by tsiflimagas** [comment]
I don't think there's any reason for a mention. There would be if adding it by edit wouldn't work. It's just the logical conclusion that the essence is to have it mentioned in the description when the PR gets merged, either by adding it from the beginning or later. As for comments, of course, I didn't think they work either, thus I didn't mention them.

**Review by patrickgold — CHANGES_REQUESTED** [review]
Thanks a lot for your changes!

The layout itself looks good, however you used the incorrect language code, the correct language code would be `et` for Estonian. Can you please rename the popup mapping file and also adjust it in the extension.json? After this this PR would be ready for merging.

**Comment by OneSheepy** [comment]
Hello!

I changed the language code around, hopefully its okay now.

**Review by patrickgold — APPROVED** [review]
Perfect, thanks a lot for adjusting the language code. Going to merge the changes in now, will release it in 0.4.0-alpha05 relatively soon.

**Comment by patrickgold** [comment]
Also I just noticed why you used `ee` - Estonia (the country) is `ee`, while Estonian (the language) is `et` - that's a really confusing abbreviation scheme ISO chose right there...

**Comment by patrickgold** [comment]
Also because I just saw that this was a point of discussion earlier on: to get GitHub to automatically link an issue to a PR you must write "Closes #XXX" (or any keyword described [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)) in the very first comment of the PR. It must the the very first comment or any commit message. I've edited your original commend so it now looks like this:

image

As you can see if GitHub detects the auto-link the word closes gets a dotted underline and if you hover it you can additionally confirm what's meant by that.

**Pull request merged**
