### PR TITLE
Theme rework (Milestone v0.4.0 / E) & Asset manager base (Milestone v0.4.0 / C)

### LINKED ISSUE #77: Follow system theme
As of now there are both darl and white themes for Florisboard, but you need to select them manually if you want to switch from one to the other, which is not super convenient if you use a scheduled dark mode, and since they keyboard is a big part of the screen and something you use a lot it is a bit impractical to have the rest of your system on it while the keyboard remains on a light mode.

It would also be awesome that when this gets added, that you could select the variation of both the light and dark themes. So, for example I changed the colours of my light theme, but I do not want them to go to default once I switch to dark mode, and viceversa. Slide, a Reddit client, does this pretty well.

### LINKED ISSUE #80: Backspace icon colour
Hey i just found your app and I'm liking it so far. I was just wondering if you could add an option to change the backspace button colour as we can with the shift and enter buttons. Thanks.

### LINKED ISSUE #131: Design-Tab Loads for a Long Time
"Long time" not as in "hours" but a long time compared to the other tabs in the FlorisBoard settings.
1 second, which is significantly longer than the other tabs.
**Environment information**
- FlorisBoard Version: 0.3.2
- Install Source: F-Droid
- Device: Samsung Galaxy S9 (a pretty fast device)
- Android version, ROM: 10

**Steps to reproduce**
1. Go to the app's settings
2. Click on 'design' on the bottom bar
3. See error

### LINKED ISSUE #136: High Battery Usage
This is in a 20 hour discharge period from 90% to 5%. The total typing time was 50 mins, and i have not opened the FlorisBoard app, just the keyboard and typed with it on another app:
Screenshot_20210109-003626_Settings
Here is AnySoftKeyboard in a different test occassion:
IMG_20210109_004127_104

**Environment information**
- FlorisBoard Version: 
- Install Source: F-Droid
- Device: Mi A2
- Android version, ROM: 10, LineageOS

### LINKED ISSUE #144: Change Keyboard-Colors According to App-Colors
Got the idea from AnySoftKeyboard. It's probably best to try it out there to fully understand it.

This supposedly is their pull-request: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1556

### PR DESCRIPTION
**Pull request by patrickgold**
This PR is a complete rework of the currently implemented theme engine and its features configurable in the Settings. Furthermore, a base for the extensions is slowly but surely being built to be able to provide extensions. (see package `ime.extension`).

Changes regarding milestone v0.4.0 / C (Extension support):
- Add AssetManager, a class which handles the I/O of asset files. This class is a key part in providing assets from any source (APK, internal storage, extension APK).
- Other Asset* classes, which enable AssetManager to work with dynamic sources and to be able to handle assets at all.

Changes regarding milestone v0.4.0 / E (Theme rework):
- Complete under-the-hood theme rework
  - The new theme better suits the new Asset format
  - The new engine completely avoids overdraw, which caused a lot of unnecessary CPU load. This brings the CPU idle usage to near zero and vastly improves battery usage. Closes #136 
  - More reliable setting of configured theme attributes.
  - Allows for theme import/export [At least in theory, a proper implementation of this will follow in the future]
  - Allows for dynamic theme creation
  - Every key can now be separately configured (Closes #80)
 - The Settings UI in the tab "Theme" got a fresh look and adds new features
   - You can now set a theme mode, which allows 4 modes: `Always day`, `Always dark`, `Follow system` (Closes #77) and `Follow time`. (See screenshots attached below)
   - Configure the day and night theme separately
   - Adapt the keyboard color to the current app (Closes #144)
   - Set a sunrise and sunset time (for the `Follow time` mode)
   - The theme tab now does not lag when being opened (Closes #131)
- Add border-less theme presets (day & night) (Idea in #118)

When this PR and any pending open PRs are merged, v0.3.3 will be released, which will contain a lot of improvements besides this too.

<table>
<thead>
<tr>
<th colspan="4">Screenshots</th>
</tr>
</thead>
<tbody>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>

### CODE REVIEW

**Comment by RickyM7** [comment]
Everything's perfect here!
A great thing is that lags within the app (which occurred when switching tabs or changing the app theme) no longer occur. I believe that these lags occurred due to the option of previewing changes of the theme on the keyboard that existed in the 'Theme' tab.

- Device: Redmi Note 4 (MIUI 11 - Android 7.0)

**Comment by patrickgold** [comment]
This PR is now pretty complete in terms of features. I will now test it, fix bugs, improve the UI and UX (input validation of text fields) and then merge this PR. All changes included here will be released with v0.3.3 tomorrow evening.

**Comment by RickyM7** [comment]
@patrickgold Sorry for randomness, but could you tell me how you did to leave the name "Screenshots" aligned and in a unique line above four images? I've tried it here on GitHub but I couldn't.

**Comment by Surendrajat** [comment]
@RickyM7 using tables(MD or HTML) I think. :)

**Comment by patrickgold** [comment]
@RickyM7 Like @Surendrajat correctly assumed I used HTML tables as a "hack" to align four pics in a row.

Here's the code for above table:

```HTML
<table>
<thead>
<tr>
<th colspan="4">Screenshots</th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="https://user-images.githubusercontent.com/19412843/104134283-de969400-5388-11eb-902e-070c6bf4b70f.jpg"></td>
<td><img src="https://user-images.githubusercontent.com/19412843/104134284-dfc7c100-5388-11eb-9db9-1568eecafc24.jpg"></td>
<td><img src="https://user-images.githubusercontent.com/19412843/104134285-dfc7c100-5388-11eb-90a2-254010e4f696.jpg"></td>
<td><img src="https://user-images.githubusercontent.com/19412843/104134286-e0605780-5388-11eb-9cf6-48ace24fe89e.jpg"></td>
</tr>
</tbody>
</table>
```

You can also use markdown tables for this but then the image heights are somewhat random, even though the pic resolution is 1:1 the same. That's why I am using HTML tables, where the browser does the job better than GitHub's markdown to HTML :)

**Comment by RickyM7** [comment]
@Surendrajat @patrickgold Thank you very much, this will help me a lot to better organize the issues that I create in the projects I follow.

**Pull request merged**
