### PR TITLE
Fix random rotated images in threema

### PR DESCRIPTION
**Pull request by lm41**
This PR tries to fix the random image orientation bug in Threema. 

Closes: #2363

### CODE REVIEW

**Review by patrickgold — COMMENTED** [review]
I've had a look at your code and currently am not sure about it. When the clipboard query() gets a request with the projection set to ORIENTATION jet you just return the orientation? I need to take a closer look at the Android docs here, atm I can't say if this behavior is correct or not.

**Comment by lm41** [comment]
I think it is the correct behavior: https://developer.android.com/guide/topics/providers/content-provider-basics#kotlin
In https://github.com/florisboard/florisboard/pull/2369/files#diff-76c7c47d41f9a377918cf21eaf428807fd8e42a1f09ae29f8d7b17d087e47cd4R95-R97 I check if the requested cols are existing in the db and then return the cursor with the requested cols.

**Comment by patrickgold** [comment]
Ok you are correct the projection array is the array of requested cols to return. However you simply join the array to a string and then compare it, you should probably say something more like `if projection contains MediaStore.Images.Media.ORIENTATION then do X`. Also then you need to check if using a joined version of projection can be used for the SELECT list statement

**Review by patrickgold — COMMENTED** [review]
Thanks a lot for the fixes. I have reviewed your approach and this version is now much cleaner and better imo. I don't have threema so I can't really test out this fix, should we merge it in like this or try finding some testers first testing the debug artifact?

**Comment by lm41** [comment]
https://github.com/florisboard/florisboard/issues/2363#issuecomment-1974898162

**Comment by lm41** [comment]
I think you can merge it in like this now.

**Comment by patrickgold** [comment]
Perfect doing that now

**Pull request merged**
