### PR TITLE
Added Option to Hide keys border

### LINKED ISSUE #87: Hide keys border
I'd like a feature to hide keys border / shadows to make something like in GBoard

### PR DESCRIPTION
**Pull request by yashx**
## Demo

https://user-images.githubusercontent.com/20506602/103399315-867cb800-4b66-11eb-835f-f43f14bbaecd.mp4

## I had some concerns with the space key but I think it looks alright

https://user-images.githubusercontent.com/20506602/103399632-e758c000-4b67-11eb-972c-756dce48b589.mp4

closes #87

### CODE REVIEW

**Comment by RickyM7** [comment]
Unfortunately this option did not work on my phone. The option does not change anything on the keyboard, i.e. keys borders are always visible.

- Device: Redmi Note 4 (MIUI 11 - Android 7.0)

**Comment by yashx** [comment]
@RickyM7 Can you try again? I have tried a different approach

**Comment by RickyM7** [comment]
@yashx Still doesn't work.

**Comment by yashx** [comment]
Well that's weird, I am using the same code to hide shadow that cut, copy, paste buttons on the top of the keyboard use.

Can you share a screenshot of keyboard after you enable it? @RickyM7

**Comment by RickyM7** [comment]
@yashx Here it is, but it literally doesn't change anything.

| Border On | Border Off |
| --- | --- |
| border on | border off |

**Comment by yashx** [comment]
No it's working. See the bottom side of every key, the shadow is absent now.

To get a keyboard similar to what I had shared above, you will need to set the same color as the background of both key and keyboard in settings.

**Comment by RickyM7** [comment]
@yashx Actually, I hadn't realized that, sorry for the confusion.

**Comment by RickyM7** [comment]
@yashx Btw, Would it be possible to make the color change occur automatically by activating this option? I think whoever asked for this option will want it.

**Comment by yashx** [comment]
@RickyM7 It's possible. But I am not sure which way will be better. 
Let's have @patrickgold decide.

**Comment by RickyM7** [comment]
@yashx Ok. Thank you for the reply.

**Comment by patrickgold** [comment]
@yashx Thanks again for your continuous great additions! Your PR at a first glance looks fine. After merging in my changes and your previous PR, I will test out this change and if everything checks out, merge this also into master!

> Btw, Would it be possible to make the color change occur automatically by activating this option? I think whoever asked for this option will want it.

IMO it would be best to let the borderless preference and the key bg color preference detached from each other, as this allows for more customization. I would though provide a `Floris Day` theme (as it existed with key borders and bg) as well as a `Floris Day (Borderless)` theme for a quick config, the same also for the night theme. Then, each user can individually fine-adjust it how they want FlorisBoard to look like.

@RickyM7 Thanks for testing out this changes and providing useful input, I really appreciate it

**Comment by patrickgold** [comment]
@yashx I have tested your proposed changes and will now merge them into master, thanks again for your contribution!

> I had some concerns with the space key but I think it looks alright

I plan to rework the complete theme logic soon, in which I will add a dynamic key themeing. This should then fix this problem for users who want the space bar to still have a bg while all other keys don't.

**Pull request merged**
