### PR TITLE
Add Material You support

### PR DESCRIPTION
**Pull request by Waelwindows**
Continued from matrix.

So far I've managed to get florisboard building on nix with `compose.material3`. Looks like i need to look into `SnyggStylesheet.kt` and maybe theme editor related stuff first. Got any clue for low hanging fruit?

### CODE REVIEW

**Comment by patrickgold** [comment]
There are multiple ways we can implement Material You (=MY) into the keyboard UI. A hot file is definitely [SnyggStylesheet](https://github.com/florisboard/florisboard/blob/master/app/src/main/java/dev/patrickgold/florisboard/snygg/SnyggStylesheet.kt), just because it is the main point where the keyboard UI retrieves its colors.

In the past I had 2 different approaches in mind:
1. Similar to how adaptive themes in 0.3.13 worked, we could inject MY in the `getProperty(...)` method, which decides based on the requested element and metadata which color should be returned. This is a lot of hard coding though, so I don't know if this is the best idea.
2. You could generate a SynggStylesheet dynamically ([like here with the base style](https://github.com/florisboard/florisboard/blob/master/app/src/main/java/dev/patrickgold/florisboard/ime/theme/FlorisImeThemeBaseStyle.kt)), once on startup and then everything the dynamic system color palette changes. Then in [ThemeManager.updateActiveTheme()](https://github.com/florisboard/florisboard/blob/06cfa34a4bf350dbed34d100f8befedcb2876906/app/src/main/java/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt#L117-L121) you select the dynamically generated stylesheet if MY is enabled. The cool thing is that SnyggStylesheet has a DSL builder, so you could write a relatively well looking dynamic stylesheet.

Generally I'd much prefer approach 2, just because the whole process is much cleaner. The problem with both approaches is that the current custom theme has no say in which surfaces should be painted what and atm I don't really have an idea how to integrate it into a sylesheet.json either.

Above info is just a hint, if you have a better idea you are allowed to draft it too :)

**Comment by patrickgold** [comment]
> Just to get a few things clear. How can we integrate method 2 with user themes?

Yeah that's the big question here. Atm approach 2 would ignore the user theme.

What we could do is the following: If Material You is enabled AND `isMaterialYouAware` is set to `true` in the user theme, then we do the following: compile the user stylesheet, but switch out ALL colors to the dynamic colors, BUT respecting the user choices for key shapes, font sizes, shadow, etc. This would be an initial middle way approach to both accept what the user has set and to take the colors from Material You.

I wouldn't compile the stylesheet every time though, only if strictly necessary (user theme has changed or system dynamic color palette has changed)

**Comment by patrickgold** [comment]
@Waelwindows do you still want to work on this feature or should we close this draft and possibly allow others to work on Material You support?

**Comment by rnayabed** [comment]
Is this currently dormant? We would really love to have monet support ☺️

**Comment by patrickgold** [comment]
Closing PR as per resolution on Matrix chat. Material You support will be added either by me or someone else in the future, however there is no ETA for this.

**Pull request closed without merging**
