### PR TITLE
Updated bn-BD layout

### PR DESCRIPTION
**Pull request by RHJihan**
This PR aims to incorporate the latest Unijoy layout into the bn-BD layout and tune the popup keys.

### CODE REVIEW

**Comment by Tarek-Hasan** [comment]
Very much thanks for your contribution, @RHJihan 
If you want to improve Bangla typing experience (word suggestion and auto-correction), you can look in #1885. In there, I listed Bangla keyboard and word-list/dictionary resources. Hope it helps.

Also, if you don't mind.
Will you be able to add Bangla support to [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard), please?

**Comment by RHJihan** [comment]
@patrickgold, are any changes or additional modifications required to merge this PR?

**Review by patrickgold — APPROVED** [review]
Seems fine to me, will merge the changes in

**Comment by RHJihan** [comment]
@Tarek-Hasan, thank you. 

> Will you be able to add Bangla support to [AnySoftKeyboard](https://github.com/AnySoftKeyboard/AnySoftKeyboard), please?

I will try. However, I cannot give a specific timeline.

**Pull request merged**
