### PR TITLE
enable basic CI

### PR DESCRIPTION
**Pull request by Surendrajat**
This PR enables GitHub Action for building the project on the push and pull requests.

### CODE REVIEW

**Comment by D3SOX** [comment]
I think it would be nice if you could also add an archive artifacts step so that it is possible to download the compiled apk

**Comment by patrickgold** [comment]
Thanks for the contribution!

I've never worked with GitHub actions before and thus don't exactly know what the action does.
If I understood the workflow syntax correctly, your added GitHub action does the following:
- Every time someone makes a PR or someone pushes to the master branch, GitHub actions will debug build the project and then either put a green tick or a red x next to the commit to indicate if the current code is build-able.
- The artifact is the output APK of that build. What I don't understand though is where it is then available for download...

Sorry if I sound like a complete newbie but like I said I've never worked with this yet and thus missing the knowledge for this topic (but I will of course catch up on that when I've some free time and see what GitHub actions can offer besides this).

**Comment by D3SOX** [comment]
You only see artifact if you merge it and look under the actions tab (https://github.com/actions/upload-artifact#where-does-the-upload-go)

Btw if you had tests (e.g. unit tests) you could also integrate them there and instantly see it something breaks.

**Comment by Surendrajat** [comment]
@patrickgold you got it right. The uploaded APK can be found in Action run (details link next to green tick). Since this repo never had any action it will not run until you add commit once. I've created a [test branch](https://github.com/Surendrajat/florisboard/tree/test) on my fork for you to see if(and how) it works. Check [this one].
We all start somewhere so it's fine :) Just let me know if `assmeble` task is the right one.

**Comment by patrickgold** [comment]
@D3SOX Thanks for the info!

@Surendrajat Thanks for the confirmation! I will play around with the GitHub actions you provided in a playground branch so i get a better feeling of how this looks like. If I feel that everything looks ok (which it seems looking at your provided test) I will merge your PR!

> Just let me know if assmeble task is the right one.

What exactly do you mean with the "assemble" task?

**Comment by Surendrajat** [comment]
Cool.
> What exactly do you mean with the "assemble" task?

I meant for the gradle task.

**Comment by patrickgold** [comment]
> I meant for the gradle task.

Oh I completely forgot that gradlew had the assemble task as well 😄, now I understand. As far as I can tell, it is the correct one!

**Comment by Surendrajat** [comment]
@patrickgold now that you've enabled actions, this one is building fine.

**Comment by patrickgold** [comment]
@Surendrajat Yes I've just seen, this automatic building is really cool imo. It makes it more easy to see at a first glance if the commit or PR actually contains fully build-able code, which is just amazing! 😄 

I will still play around little bit more to feel more safe, then merge your changes!

**Comment by RickyM7** [comment]
Maybe some minor improvements can be made, such as adding the app name, version and debug build number in the apk, just as it is done in App Manager. Take a look [here](https://github.com/MuntashirAkon/AppManager/tree/master/.github/workflows).

**Comment by Surendrajat** [comment]
@RickyM7 It makes sense for AppManager as they are trying to get notifications on telegram on each build. But here, IMHO, having a generic name for a continuous build is better as it will only get confusing for a debug build to have the same name and version as a release build. People might want to install it over their release version too.

However, It makes sense for release automation (on a tag) and I can add that if @patrickgold wants but it will need the Keystore to be public(passwords can be secret). But let's do that in other PR once this is merged.

**Comment by RickyM7** [comment]
@Surendrajat It makes sense, thanks for the answer. Another thing, I took the liberty to mark your PR in some projects that I follow to serve as a base for the implementation of debug builds automation, is it okay for me to do that?

**Comment by Surendrajat** [comment]
@RickyM7 Absolutely. It's only better as I can only do it for a few projects I like.

**Comment by RickyM7** [comment]
@Surendrajat Thank you very much!

**Comment by patrickgold** [comment]
> However, It makes sense for release automation (on a tag) and I can add that if @patrickgold wants but it will need the Keystore to be public(passwords can be secret). But let's do that in other PR once this is merged.

@Surendrajat tbh, i rather want my keystore to stay private and I just manually upload the signed APK to the corresponding release, at least for now.

**Comment by Surendrajat** [comment]
@patrickgold sure. That's only needed *if* you want to automate the release process too.

**Comment by patrickgold** [comment]
@Surendrajat I've merged your changes into master, thanks again for your contribution! I don't know though why GitHub won't recognize this (I've done the merge locally in the cli).

**Comment by patrickgold** [comment]
Nvm, as I've squashed together your commits before merging, GitHub can't keep a reference to the merge. Closing this PR thus manually, as it has been merged with e2c784f .

**Pull request closed without merging**
