### PR TITLE
Add Rusyn Language Language Set, Layout, Popups

### PR DESCRIPTION
**Pull request by svvvst**

### CODE REVIEW

**Comment by svvvst** [comment]
@patrickgold, am I doing this right?

**Comment by patrickgold** [comment]
Thanks for your pull request, really appreciate it!

I haven't tried out your layout addition in runtime yet, but looking at the source changes it looks super clean and well done! Will merge in your changes before I make the beta09 release this week!

**Comment by svvvst** [comment]
Thanks Patrick! Appreciate it. This is my go-to keyboard app right now and my first time building an app from source or contributing to a project on GitHub. Great learning experience.

**Comment by patrickgold** [comment]
I've reviewed your changes, added the missing popup mapping definition from the extension.json manifest and will now merge your changes in. Will be released in 0.3.14-beta09!

**Pull request merged**
