### PR TITLE
Add experimental spell checker & extension support

### LINKED ISSUE #286: Spell check not always working
Hey Ive noticed that spell check doesnt always work. In fact in some apps, I haven't seen it work at all. One of those is Snapchat.

### LINKED ISSUE #501: Implement system spell-checker
Hi Patrick,

I've been following the evolution of Florisboard for a few months, and am starting to really enjoy it ! :smile:

One of the things I have noticed is that Florisboard is the only FOSS keyboard that I know which support actual multilingual suggestions (aka, without manually changing the type). This is **really** useful, please keep that option !

However, I've noticed the native Android spell-checker doesn't properly support multilingual suggestions, so word often get flagged as invalid even though they are properly recognized by Florisboard.

I've personally disabled that in the meantime - but, considering Florisboard already uses dictionary files, do you think it would be possible to implement a system spell-checker like GBoard does ?

**Edit:** Just to be clear, I think this may be a low priority one, since we can always click on a word and use the suggestion bar as a spelling corrector. It just won't highlight the wrong words.

Thanks !

### PR DESCRIPTION
**Pull request by patrickgold**
After a long period of development and trial-error, this PR finally provides a first usable preview of a spell checker implementation for FlorisBoard. Additionally, an experimental extension pack format and parser is introduced (currently though only internally usage, but in the future intended for all sorts of stuff). As the changes are huge, this PR is split up in two sections.

If you want to help with improving spell checking and finding bugs, crashes etc. in this early stage, feel free to download the debug APK and try out spell checking on your device! Any feedback is highly appreciated and will contribute in making the spell checker better for everyone :)

**Note: currently there's an issue with the linked ICU libraries, causing the debug APK to be of a massive size. I am working on reducing and fixing this issue!**

# Spell checking

To provide spell checking services, FlorisBoard implements [Nuspell](https://nuspell.github.io/), with the help of [ICU](https://github.com/unicode-org/icu) for proper interpretation of special UTF-8 characters. Nuspell is a vastly improved implementation of the original Hunspell library (which was used earlier in development, but caused massive problems with special characters). FlorisBoard does not ship with any pre-installed Hunspell dictionaries, but supports the import of any Hunspell/Nuspell dictionary provided by the user (`.aff` and `.dic`). There are no language restrictions, the user must just find a spell checker dictionary which works best for their language/dialect. **Note: in this experimental preview import formats are limited to a few selected sources, see in-app for more details**

As the spell implementation is still experimental, spelling suggestions may be empty strings or still display boxed question marks. If this happens when trying out this PR's debug APK, feel free to comment down below with the link to the dictionary used and which device/Android version you are using.

The Settings UI for spell checking is currently a bit "wonky" and ugly, but does the job. It will be overhauled in the period of the next weeks. The "fine-tuning" options currently do nothing, but will be implemented before releasing an experimental preview on the beta channel.

To enable FlorisBoard as a system spell checker, go to FlorisBoard Settings > Home > Spelling prefs > Active spell checker and then select FlorisBoard Debug.

## Samsung, Samsung, Samsung...
I've seen several times that there are some issues with spell checking ans Samsung, but could not verify any of those issues on my Galaxy A21 physical phone. If you are a Samsung device owner and experience any crashes or spell checking simply does not work, please also leave a comment with the details of your device and Android version. This help is much appreciated!

Closes #286 
Closes #501 

# Extension support

Additionally this PR internally adds a basic foundation for future extensions of all sorts. The package `res/ext` contains all currently important code. Each Extension is a zipped file containing files and sub-directories and must contain an `extension.json` conforming to [this](https://github.com/florisboard/florisboard/blob/57b3b7b5d74699205ac44bf90b5abafd0ed75863/app/src/main/java/dev/patrickgold/florisboard/res/ext/ExtensionConfig.kt) interface. Extension support is far from done though and needs quite some rework to be viable for frontend use, but imported spelling dicts are already internally converted and used as such extensions.

### CODE REVIEW

**Comment by sabzo** [comment]
@patrickgold I'm having a hard time testing this using version `0.3.13`. How do we activate the spelling features? I don't quite see the new items and I'm getting "an error occured while indexing the install spellchecker dictionaries..."  the "where do i get spellcheckers" just points to the github issues.

**Comment by patrickgold** [comment]
> "an error occured while indexing the install spellchecker dictionaries..."

On first use in the experimental version this error can be ignored (it shows because the dictionary tree for spelling is not configured yet). The "where do i get spellcheckers" shouldn't point to the GH issues, but to the internal fragment which explains where to get spelling dictionaries. If it doesn't this would be very strange, but you can try out a dictionary from [here](https://addons.mozilla.org/en-US/firefox/language-tools/) and then import it via the green plus.

**Comment by X-yl** [comment]
Whoa 2.7 million new LOC?! Shouldn't the new libraries be [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?

**Comment by patrickgold** [comment]
> Whoa 2.5 million new LOC?! Shouldn't the new libraries be git submodules?

You are right, it should be put in a git submodule. Will do that when I fix the ICU build size.

**Comment by patrickgold** [comment]
@X-yl I've added the ICU build module as a submodule, thus reducing the amount of new source code lines drastically. We are now at 136k instead of 2.55mil, still I can't get rid of the pre-compiled Unicode header files (which I assume are like 70% of the 136k). Next I will see how to bring down the ICU data library size (it is the culprit for the astronomically high APK size) and then continue with fixing bugs in the Kotlin.

**Comment by BrudiBanani** [comment]
I can not update debug versions of florisboard.
Is it intended? I always need to remove florisboard debug first and than install new artifact.

**Comment by patrickgold** [comment]
> I can not update debug versions of florisboard.
Is it intended? I always need to remove florisboard debug first and than install new artifact.

Normally debug versions should be update-able but some devices dislike the fact that the versionCode attribute does not change (as these debug builds are not official releases but as the name implies, experimental and only for testing), thus requiring a re-install.

**Comment by Luensche** [comment]
In the title of the pr is a spelling mistake:
Is: Add experimental spell checker & experiemntal extension support
Correct: Add experimental spell checker & experimental extension support

**Comment by Waelwindows** [comment]
I feel like having experimental 2 times is a bit redundant. But whatever this PR's title is, it shouldn't matter as long as it's legible

**Comment by patrickgold** [comment]
Thanks for letting me know, fixed the title of the PR!

**Comment by patrickgold** [comment]
This PR is now ready to be merged into master, so I can release it on the beta channel as an experimental tagged feature. Further improvements will be done in an additional PR after gathering more feedback from beta users.

**Pull request merged**
