### PR TITLE
[OBSOLETE] Switch emoji and one-handed mode extended popup / Add Gboard Day theme

### PR DESCRIPTION
**Pull request by itskareem**

### CODE REVIEW

**Comment by patrickgold** [comment]
Thanks for your PR, I really appreciate it! Your PR seems to add two different things at once: the switch position (which is perfectly correct) and the GBoard like day theme. Normally it would be better if you separated these into two PRs, so one thing can be checked at a time.

I haven't checked your Gboard theme on a real device yet, but in line 2-4 the meta data needs to be updated to be properly processed within FlorisBoard. Also, please use your username in the author field so this can be shown correctly in the UI.

**Comment by itskarim** [comment]
Sorry but this is my first contribution on a real project

**Comment by itskarim** [comment]
Sorry but this is my first contribution on a real project

**Comment by patrickgold** [comment]
There's always a first time for everything and you can do nothing wrong here, so I will assist you :)

As this is your first contribution (and except for the meta data a very clean one), i will make an exception and will allow the two separate things at once. Like I said, the switch position thing is perfect and needs no change. The `gboard_day.json` file though needs this meta data at the top:

```json
    "name": "gboard_day",
    "label": "Gboard Day"
    "authors": [ "itskareem" ],
```

This meta data allows FlorisBoard to uniquely identify the theme and display essential info like the name of the theme and its authors in the Settings UI. 

Hope I could help. If you need any assistance, don't hesitate to ask me here in this thread!

**Comment by patrickgold** [comment]
Obsoleted by #258 .

**Pull request closed without merging**
