### PR TITLE
Add keyboard layouts optimized for swype input

### PR DESCRIPTION
**Pull request by jeremiah-miller**
Layouts were found [here](http://sangaline.com/post/finding-an-optimal-keyboard-layout-for-swype/) and [here](https://jasmcole.com/2017/06/04/swype-right/), added as mentioned in #76

### CODE REVIEW

**Comment by dashezup** [comment]
Nice I would like to try it. I've been using Sangaline's one for a while (by patching Gboard APK to include that layout).

Was those layouts ever been include in any of other keyboard app? or this could be the first one?

Sangaline didn't name it in that blog article. @sangaline would you name the best swype keyboard layout you designed? such like after your name Sangaline or just DGHP?

**Comment by jeremiah-miller** [comment]
It was referred to as DGHP in the paper they wrote, so that's what I went with. Personally i think DGHPAS is nicer, but this is fine too http://arxiv.org/abs/1503.06300

**Comment by dashezup** [comment]
> It was referred to as DGHP in the paper they wrote, so that's what I went with. Personally i think DGHPAS is nicer, but this is fine too http://arxiv.org/abs/1503.06300

that's ok then, I didn't know this before.

**Comment by jeremiah-miller** [comment]
How do you pronounce it in your head/if you were to say it out loud? I think i'm gonna go with pronouncing it like "dope", as if it was "dough" without any vowels and then 'p' on the end. But i'm curious if you have any other ideas :) (this is just small talk, feel free to not respond or whatever lol)

**Comment by dashezup** [comment]
yeah it's a bit strange to try to pronounce DGHP.

I named it Sangaline on my Gboard patch (been using it longer than 1 year iirc). I'm more comfortable to call it with its inventor's name, I also use Dvorak (more specifically Programmer Dvorak on desktop/laptop) which is also named after the inventor's name. But since Sangaline named it DGHP in that paper it may be fine to just call it DGHP.

It's kind of fun to make others to confused when you were using a custom keyboard layout. although in most cases they wouldn't surprised cuz I use Dvorak on desktop, they mostly thought it's also Dvorak on my phone.

**Comment by sangaline** [comment]
I'm excited to see this, thank you so much for putting it together and looping me in. I've actually never had the opportunity to use the keyboard myself, and I'm very much looking forward to giving it a try!

It's unfortunate that the keyboard doesn't start with something more pronounceable or memorable. We called it DGHP in the paper because we needed a convenient way to refer to that specific layout, but I wasn't really thinking about the implications as a user-facing name at the time. I agree with @jeremiah-miller that DGHPAS seems a bit nicer than DGHP. I wouldn't be bold enough to suggest "sangaline" as a name myself, but you certainly won't hear any complaints from me if you decided to go with that :-). It has the advantage that Googling ["sangaline keyboard"](https://www.google.com/search?q=sangaline+keyboard) brings up the [blog post](http://sangaline.com/post/finding-an-optimal-keyboard-layout-for-swype/), the open-source [dodona keyboard design/simulation framework](https://github.com/sangaline/dodona), a [Hacker News discussion about the keyboard](https://news.ycombinator.com/item?id=9355276), and [the paper](https://arxiv.org/abs/1503.06300) as the first four results. Similar searches for ["dghp keyboard"](https://www.google.com/search?q=dghp+keyboard) and ["dghpas keyboard"](https://www.google.com/search?q=dghp+keyboard) turn up nothing relevant.

**Comment by jeremiah-miller** [comment]
I think "sangaline keyboard" is the best bet, but i'll be away from my computer till sunday night or monday, so if someone else could make the change i'd really appreciate it, if not i can do it then!

**Comment by dashezup** [comment]
> I've actually never had the opportunity to use the keyboard myself, and I'm very much looking forward to giving it a try!

This patched old version of gboard apk is the one I'm using. it's mainly based on [the script in this gist](https://gist.github.com/empathicqubit/c075158e915e4d85651bb83d4196cab4), layout named Sangaline. I haven't try to patch gboard apk for a while because it has signature verification and it's a boring work to bypass it by editing smali codes.

https://ezup.dev/tmp/2wdipiy5_com.google.android.inputmethod.latin_26890814.apk (link available for 30 days)

It has symbols hidden as well. It seems that Florisboard does not have options to hide those elements to make it clean like this for now.



> I think "sangaline keyboard" is the best bet, but i'll be away from my computer till sunday night or monday

you can also edit on GitHub web UI. And this may could be "squash and merge".

**Comment by jeremiah-miller** [comment]
cc @jasmcole

**Comment by jasmcole** [comment]
> cc @jasmcole

Cool! Thanks for the ping - I'll have to give this a go.

**Comment by jeremiah-miller** [comment]
Have you all been using these and comparing them? So far it seems to me that nalmy is easier for real life use, since it's primary goal is to minimize finger travel, whereas the sangaline board is trying to minimize errors. That's great, except it does that by making swipe patterns longer and more complex, which seems to make swiping less comfortable or convenient. It would be interesting to see the error rate reduction that nalmy has when running it through dodona

**Comment by dashezup** [comment]
> Have you all been using these and comparing them? So far it seems to me that nalmy is easier for real life use, since it's primary goal is to minimize finger travel, whereas the sangaline board is trying to minimize errors.

I wondered about that as well, that's a good summary. I've only been using Sangaline layout, tried NALMY a little bit, and I don't think I can get used the two layouts. from my experience:

- with sangaline layout, for lots of words, I need to across almost the whole width of the keyboard to type them
- dvorak is just bad for swype, QWERTY may be fine for swype typing especially comparing to dvorak
- it's easier to achieve touch-typing-alike effect with sangaline layout, because most of used letters are either located at left side, right side or center which are easily to be located. while NALMY has most used letters at the center, most uncommon letters on left side and right side, usually you need to pay more attention on the center of the keyboard with eyes while typing (idk if this still matter if the one get used to this NALMY layout).

regarding the finger traveling problem on Sangaline, one hand mode may be the solution for that but I'm not fan of it. I feel more comfortable when the keyboard is centered on phone screen. it should be fine on phones with smaller size of screen, such like old iPhone or iPhone SE (4.7 or 5.5 inch), but iPhone iOS is not that friendly for using modified Apps compare to Android.

btw it should be **swype** instead of **swipe** you may edit the issue title as well

**Comment by jeremiah-miller** [comment]
I think you're right that sangaline might be better with small keyboards, but even then it would be annoying to always be swyping back and forth. 

> while NALMY has most used letters at the center, most uncommon letters on left side and right side, usually you need to pay more attention on the center of the keyboard with eyes while typing (idk if this still matter if the one get used to this NALMY layout).

I've been using the [flow keyboard](https://play.google.com/store/apps/details?id=com.enchantedcode.flow) for a while and it's like that (but takes that philosophy of most-used-in-the-center to the next level). Once you get used to it it's super fast and easy, if it had a better emoji selector it's all I'd use

**Comment by patrickgold** [comment]
Sorry for the long delay on the review of your additions, I was distracted by the spell checker implementation the last few weeks.

I've reviewed and tested out the layouts on my local testing rig and everything looks fine, the codes match up with the labels and auto-capitalization works also fine. Thanks for the work, really appreciate it :)

If it is ready for you I can merge in the changes and add it to the beta05 release (which will come out in the next few days after working through the backlog).

**Comment by jeremiah-miller** [comment]
No worries, yeah it's all set to integrate! Thanks!

**Comment by patrickgold** [comment]
Perfect, will merge it then!

**Comment by jeremiah-miller** [comment]
cc @jasmcole I've been using NALMY for about a month now and I think I've got a pretty good hang of it, however I think swapping 'R' and 'S' would help reduce a lot of errors (so I don't type "it" when I want "is" or vice versa). And there might be a few other small optimizations here and there, but I think that's one of the biggest ones. I'll add any more I think of here and then try out a tweaked version of it and if it's better then I'll see about getting it added. If anyone else has any tweaks in mind drop them here too so I can try them out.

Also if this isn't the best place for this kind of discussion I'm happy to move it, I wasn't sure where would be best since I also want to get ideas from other people who might've been using NALMY for a bit now

**Comment by jeremiah-miller** [comment]
"She"/"the" are another one that would be fixed by swapping 'r' and 's'

Some other ones with less obvious solutions:

- "I'm"/"I'll" are way to easy to mix, could be fixed by moving 'm' or 'l' to the bottom of the keyboard

- "dipping"/"doing"/"dropping" are extremely similar, but i have no idea what a simple fix could be

**Pull request merged**
