### PR TITLE
Re-implement basic emoji palette view

### LINKED ISSUE #123: Increasing the font size of emojis
Looks like the emojis are small comparing to other keyboards
USER_SCOPED_TEMP_DATA_orca-image--121858432

### LINKED ISSUE #268: Emoji recents / most used category / history
A most used emojis category ( button ) that will keep the 40 - 50 most used emojis for quick access like in many other android keyboards.

The button will have a clock icon and will be the default category when you switch in emojis screen, it also will be the most left one.
It would be nice that each icon on the most used screen can be manually removed ( maybe with long press context menu ).

For example 
[Keyboard Image](https://imgur.com/WMI0lPa)

### LINKED ISSUE #522: Correct line-thickness for emoji view buttons
I think the Emoji-View might look less like a completely different app if the buttons on the bottom were actual buttons.

At least `ABC` and the delete button should follow the keyboard's design by being buttons.

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

### LINKED ISSUE #552: Some smileys are not displayed in dark mode
#### Short description
In florisboard 0.3.10 beta 04, i enabled automatic in app theming, when the keyboard is dark smileys categories won't appear.

#### Environment information
- FlorisBoard Version: 0.3.10beta04
- Install Source: GitHub
- Device: Meizu M6 note
- Android version, ROM: AOSP Extended 4.6 / android 7.1.2

Screenshot:
Screenshot_20210401-235734

### LINKED ISSUE #783: Emoji button have different color when orientated
I have purple primary, primary (dark), and accent

Screenshot_20210501-184414

Screenshot_20210501-184420

- FlorisBoard Version: 0.3.11 beta 2
- Install Source: Github
- Device: Asus Zenfone Max Pro M1
- Android: 9, stock

### LINKED ISSUE #877: Emoji popups not showing on any emoji in the right-half of the emoji panel
#### Short description
The emoji popups show in the first half of the emoji panel but not the second half. For example, 

#### Steps to reproduce
1. go on the "people" emoji category. 
2. Long press on any emoji on the first column.
3. Slide fingers across popup. (notice that this works)
4. Now go the last column on the same row.
5. Long press (this won't bring up emoji screen).
6. If emoji screen pops up, it will flash, but not remain constant enough for user to choose a popup.

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

### LINKED ISSUE #934: sometimes emoji below an emoji gets an emoji gets clicked
Steps to reproduce 
1: switch to emoji panel
2: tap on "🤔" continously in slight down way and sometimes the emoji right below it"😬" gets clicked.
Screenshot_2021-05-24-15-01-46-325_org mozilla firefox

### LINKED ISSUE #944: Favorite emoji and most recent emoji menu
A recent emoji list (preferably with a variable sized history) would make the emoji keyboard much more usable.

Additionally, a favorite emoji menu would be very helpful for a personal project of ours, which involves heavy use of emoji.

I would love to contribute some code. If anyone has pointers as to how to get accustomed to this codebase I would appreciate it.

### LINKED ISSUE #1337: Emoji Skintones cannot be chosen for emojis on second right of the screen
#### Short description
The emoji buttons on the second right half of the panel do not show properly

#### Steps to reproduce
1. Go to  Emojis
2. Click on the "Peoples" category
3. Choose any emoji on the right side of the screen
4. Notice that other skin tones cannot be selected besides the yellow one

emoji_skin_tone_bug

#### Environment information
- FlorisBoard Version: Current Master branch ( Release v0.3.14-beta04)
- Install Source: Github
- Device: Android Emulator
- Android: 11

### PR DESCRIPTION
**Pull request by patrickgold**
This pull request re-implements a basic emoji palette UI for 0.3.14 stable.

See #1235

Closes #123 
Closes #268 
Closes #522 
Closes #552 
Closes #783 
Closes #877 
Closes #934 
Closes #944 
Closes #1337

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
Well... feedback as of commit `109c323` ....
The emojis seem to be bigger? Looks like they're being cut off at the top and bottom.....
Screenshot_2022-02-23-13-13-06-34

**Comment by patrickgold** [comment]
That looks... weird I agree. They are certainly not that big on my testing devices. Seems like I have to find a way to auto-scale the emoji font size to prevent clipping from occurring.

> Also... emojis with multiple colors seem to be having several bugs

Could you elaborate further on that?

**Comment by suhan-paradkar** [comment]
Welll... for starters thepicker for coloured emojis seem to mix up with the non colored ones (just need to add a background)...
Also, the keyboard closes itself whenever I press the backspace button in emoji view

https://user-images.githubusercontent.com/76830230/155299518-fd46d902-71f0-4ee4-b826-3003a2d29e6c.mp4

The above video shows both bugs..... I also experienced a bug where a coloured emoji is automatically erased after its been typed... but I am not able to reproduce it now.....

**Comment by patrickgold** [comment]
Ah that's an issue with themeing: Currently only Floris night contains style rules for emojis, thus this issue occur. Easily fixable for the Floris Day default theme. Still, this will be a major issue for users with custom themes, because their stylesheet file will not auto-update with the corresponding emoji rules.

The delete key bug has nothing to do with the emoji palette itself but with the general buginess of the preview field. If you try out the delete key in any other app it should work.

**Comment by patrickgold** [comment]
@suhan-paradkar For the font size issue: The best solution for now is to either control the font size manually via a custom theme or via the font size multiplier (in Settings > Keyboard).

As for the theme issue: the core themes now all support the emoji view perfectly, when using custom themes there are fallback colors, so at least no transparent popups exist anymore. Still, you need to adjust your custom theme in order to get the exact appearance as with the core themes.

**Comment by patrickgold** [comment]
@suhan-paradkar For the font size issue: The best solution for now is to either control the font size manually via a custom theme or via the font size multiplier (in Settings > Keyboard).

As for the theme issue: the core themes now all support the emoji view perfectly, when using custom themes there are fallback colors, so at least no transparent popups exist anymore. Still, you need to adjust your custom theme in order to get the exact appearance as with the core themes.

**Comment by tsiflimagas** [comment]
There seems to be an issue with Android 12

`FATAL EXCEPTION: main
Process: dev.patrickgold.florisboard.debug, PID: 32405
java.lang.IllegalArgumentException: dev.patrickgold.florisboard.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.pushNotification(CrashUtility.kt:284)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.pushCrashMultipleNotification(CrashUtility.kt:317)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$Companion.access$pushCrashMultipleNotification(CrashUtility.kt:48)
	at dev.patrickgold.florisboard.crashutility.CrashUtility$UncaughtExceptionHandler.uncaughtException(CrashUtility.kt:399)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:45)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:39)
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:146)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7837)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by patrickgold** [comment]
@tsiflimagas This crash seems to have occurred while pushing the notification for another crash... Does the crash report include any other stacktrace?

**Comment by tsiflimagas** [comment]
There's no notification actually, the keyboard just freezes. I noticed that there was a crash in the logcat, so I captured that using [Scoop](https://github.com/TacoTheDank/Scoop). But since that's the case, I'm sending a complete logcat (filtering FlorisBoard's pid, so tell me if you need a full logcat).
[floris.txt](https://github.com/florisboard/florisboard/files/8144152/floris.txt)

**Comment by patrickgold** [comment]
@tsiflimagas I (hopefully) fixed the crash in the crash utility in #1602, could you please try it out if a) the crash dialog notification now comes up as usual and b) post the actual crash log here? This would incredibly help, thanks a lot!

**Comment by Yurieaijoker** [comment]
My device also crashes using the latest build same as the issue above my device is android 10 emui 10.1.1

**Comment by Yurieaijoker** [comment]
Florisboard debug also crashes on my device using the latest debug build same as the issue above my device is huawe nova 7se android 10 emui 10.1.1

**Comment by patrickgold** [comment]
@tsiflimagas @Yurieaijoker does PR #1604 fix the crash for you? The changes in the PR are, that EmojiCompat now uses the default loading method and if it is not loaded, I will fall back to using the conventional way of checking emoji support.

**Comment by tsiflimagas** [comment]
Yes, it's fixed 😁😄🎉 (used some emojis too)

**Comment by patrickgold** [comment]
Perfect, great to hear! Now I just gotta investigate why one of my test devices lags horribly in the emoji view (seems to be a recomposition issue), then I can release it to the beta branch.

Thanks again for testing the debug builds out and pointing me to the crashes, I think this saved me from an unanticipated crash report wave after I made the release :)

**Comment by tsiflimagas** [comment]
No problem!
About the lag, I'm also experiencing it. At first I thought it's because it is a debug build (debug builds always have inferior performance), but then I made a beta build and that also lagged. Though, once again, after force running dexopt for the package, it seems fixed.

**Comment by patrickgold** [comment]
> About the lag, I'm also experiencing it. At first I thought it's because it is a debug build (debug builds always have inferior performance), but then I made a beta build and that also lagged.

Hmm yeah in the last hours I did extensive debugging and backend improvements to the emoji palette, and it now runs a lot smoother. Although a tiny lag still exists on that device, but for now that's the best I can do. On my other devices it runs butter smooth though.

Important to consider is though that only the release builds are (almost) lag free, the debug build internally do so much work that there's a lot of lag (but if it is only in debug I don't care too much).

> Though, once again, after force running dexopt for the package, it seems fixed.

That's very interesting, normally this command should be invoked automatically for every app that is installed. Does this command also have positive effects on other apps if manually invoked or is this a FlorisBoard thing only?

**Comment by Yurieaijoker** [comment]
Yup fixed crashing coz of emoji fixed. Thank you

**Comment by tsiflimagas** [comment]
> in the last hours I did extensive debugging and backend improvements to the emoji palette, and it now runs a lot smoother

It's much better here too, almost great I could say.

> normally this command should be invoked automatically for every app that is installed

I remember reading this https://source.android.com/devices/tech/dalvik/configure which states that optimizations aren't run right away, but while device is idling and charging (though it mentions pixel as an example, so maybe that's not the case for other devices? Yet, custom roms copy a lot of stuff from pixels, and I'm using one.). About other apps, I can't say I really notice some difference, though I don't ofter force run dexopt. Perhaps there's some little improvement, but I don't want to mix it up with placebo. I can say for sure that there's some difference in general performance when running dexopt for all packages on a fresh rom setup. But for FlorisBoard it feels like it fixes something, more than improving it. Sometime ago I wrote on matrix about this observation (I don't know if you can recall since some time has past and you seem to have a lot on your plate).

**Pull request merged**
