### PR TITLE
Smartbar Quick Action Rework + directly related keyboard logic changes + incognito mode

### LINKED ISSUE #153: Add the ability to access incognito/private mode from smart bar preventing the personal dictionary from learning new words

### LINKED ISSUE #617: Ability to set private/incognito mode to always off
A number of apps tell the keyboard to turn private mode on. For less privacy-friendly keyboards that makes sense, but as the data in FlorisBoard never leaves the user's device, the user could benefit from customised suggestions (when implemented) without compromising their privacy.

I therefore request the ability to turn private mode off and gather data from my typing for my own use, no matter what the app I'm using suggests, please.

PS: Thanks for all your hard work :)

### LINKED ISSUE #1094: Long press smartbar items for description
Make it possible to longpress a button on the smartbar to get a description.

Example:

https://user-images.githubusercontent.com/50382414/126852189-3145643a-7af9-4609-8f19-66ef5e18a01c.mp4

### LINKED ISSUE #1561: Keyboard height changes when switching between ABC layout & ?123 layout with "Number row" enabled
#### Short description
With the "number row" enabled (above the letters & below the smartbar), the keyboard will change in height when switching between the letter mode (ABC) and number mode (?123). (Sorry, it's late and I'm not totally sure what these modes are called...)

 

In version 0.3.13 (and likely earlier), the height of the keys themselves increased when switching from ABC -> ?123. I'm not sure whether this approach would still be viable, given all the changes with theming and whatnot.

 

I can only recall the height change being an issue in Termux, in which it lead to some graphical corruption of the terminal interface. I don't exactly recall the circumstances; it's likely that an ncurses UI was involved, as the program isn't particularly fond of terminal size changes.

Other than that, it's just mildly annoying...

#### Steps to reproduce
1. Enable "Number row" under "Keyboard" in settings
2. Open the keyboard
3. Switch between ABC mode and ?123 mode
4. The keyboard height changes

#### Environment information
- FlorisBoard Version: 0.3.14-beta10
- Install Source: F-Droid (IzzyOnDroid repo)
- Device: Google Pixel 4a
- Android: 12 (build SQ1A.220105.002)

### LINKED ISSUE #1612: Re arrange smartbar
Option to re arrange or to cutomize the arrangement of the smartbar icons. Thank you

### LINKED ISSUE #1674: [v0.3.14rc3] Non functional arrow keys in quick access bar
The arrow keys act unexpected for two reasons: 
1 Each press on the arrow keys brings up the word prediction again (shouldn't it stay until I press the twisty another time?)

That behaviour made me think "maybe that is intended and a long press is needed?"

2 A long press, however, locks the arrow key, resulting in a repeatedly no end moving cursor and a pulsating smartphone, as long as FlorisBoard is active. (The stuck/locked key can only be stopped by force quitting FB, pressing other keys seems to have no effect.)

FlorisBoard v0.3.14 rc3 (from F-Droid) 
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 98.0.4758.87
Motorola Moto G4
device not rooted

### LINKED ISSUE #1781: SmartBar icons too small Landscape mode
Can Make it the same size as the icons in secondary action row, those icons are too small in landscape.

### LINKED ISSUE #1946: Western (Extra symbols) with number row ignores vertical spacing
#### Short description
Having "Western (extra symbols)" and enabling the number row causes the symbols keyboard/mode to ignore vertical key spacing

#### Steps to reproduce
1. Choose Western (Extra symbols) as your symbols layout
2. Enable the number row

#### Environment information
- Version: 0.4.0 
- Install Source: F-Droid 
- Device: Samsung A01 
- Android: 11

### LINKED ISSUE #2013: Support long press for left/right/undo/redo
Just like backspace supports long press.

Thanks

### LINKED ISSUE #2020: Crash on landscape mode
#### Short description
Today i wanted to test the new features that you made on Smartbar rework PR to see new option overflow menu everything is good and works great i like it but it have a small bug when you use phone in landscape mode(horizontal mode) and click on overflow menu the keyboard stops working and suddenly crash.

#### Steps to reproduce
1. Go to 'Any app in landscape mode'
2. Click on 'Overflow menu'
3. See crash

#### Environment information
- FlorisBoard [0.4.0-debug-7be6c13](https://github.com/florisboard/florisboard/commit/7be6c135ef7fb54624c1ab62b1a7f14efd823bb4) (88)
- Device: Samsung SM-G781B (r8qxeea)
- Android: 12 (cn=S sdk=31)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2022-08-22T13:09:52.780406Z
Manufacturer        : samsung
Model               : SM-G781B
Product             : r8qxeea
Android             : 12 (cn=S sdk=31) [SP1A.210812.016.G781BXXS4FVF3]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 3.77 GiB (68.65% used, 5.50 GiB max)
Font scale          : 0.9
Locales             : en-GB

======= APP INFO =======
Package             : dev.patrickgold.florisboard.debug
Name                : FlorisBoard Debug
Version             : 0.4.0-debug-7be6c13 (88)
Build type          : debug
Build commit hash   : 7be6c135ef7fb54624c1ab62b1a7f14efd823bb4
Java heap memory    : 36.91 MiB (14.42% used, 256.00 MiB max)
Native heap memory  : 30.94 MiB (96.19% used, 32.17 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : false
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1661173784145.stacktrace</summary>

```
java.lang.IllegalArgumentException: Requested element count -2 is less than zero.
	at kotlin.collections.CollectionsKt___CollectionsKt.takeLast(_Collections.kt:914)
	at dev.patrickgold.florisboard.ime.smartbar.quickaction.QuickActionsOverflowPanelKt.QuickActionsOverflowPanel(QuickActionsOverflowPanel.kt:55)
	at dev.patrickgold.florisboard.ime.text.TextInputLayoutKt$TextInputLayout$1.invoke(TextInputLayout.kt:63)
	at dev.patrickgold.florisboard.ime.text.TextInputLayoutKt$TextInputLayout$1.invoke(TextInputLayout.kt:55)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2363)
	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2653)
	at dev.patrickgold.florisboard.ime.text.TextInputLayoutKt.TextInputLayout(TextInputLayout.kt:84)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3$1$1.invoke(FlorisImeService.kt:605)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3$1$1.invoke(FlorisImeService.kt:598)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3.invoke(FlorisImeService.kt:598)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2$3.invoke(FlorisImeService.kt:571)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at dev.patrickgold.florisboard.lib.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:99)
	at dev.patrickgold.florisboard.lib.snygg.ui.SnyggSurfaceKt$SnyggSurface$1.invoke(SnyggSurface.kt:52)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.lib.snygg.ui.SnyggSurfaceKt.SnyggSurface(SnyggSurface.kt:49)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(FlorisImeService.kt:563)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$2.invoke(FlorisImeService.kt:562)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at dev.patrickgold.florisboard.FlorisImeService.ImeUi(FlorisImeService.kt:562)
	at dev.patrickgold.florisboard.FlorisImeService.access$ImeUi(FlorisImeService.kt:137)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(Unknown Source:6)
	at dev.patrickgold.florisboard.FlorisImeService$ImeUi$3.invoke(Unknown Source:10)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2363)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2630)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3217)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3195)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:336)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3195)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3160)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:748)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:792)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@7295976, androidx.compose.ui.platform.MotionDurationScaleImpl@d213b77, StandaloneCoroutine{Cancelling}@c4ec3e4, AndroidUiDispatcher@391104d]

```
</details>

### PR DESCRIPTION
**Pull request by patrickgold**
This PR reworks the backend of the Smartbar quick actions, implementing the actions overflow menu and drag&drop for customizing the order (in an additional screen due to technical limitations). Also some nasty bugs and issues are fixed. Additionally the clipboard and cursor row is removed and each of it's keys are now offered as quick actions. This allows for full customization of the order for every user itself.

2 suggestion-related actions are introduced: Force incognito mode and Autocorrect toggle (on/off), the latter being only a placeholder atm. Also the suggestion candidate row will be fine-tuned, so it interacts more smoothly with the action row (if the shared action/candidates layout is used).

Closes #1094 
Closes #1561 
Closes #1612 
Closes #1674 
Closes #1781 
Closes #1946 
Closes #2013 
Closes #2020 

Closes #153 
Closes #617

### CODE REVIEW

**Comment by KLaurence** [comment]
This is a small UI change, but can we highlight the smartbar-action overflow button when the overflow menu is active?

**Comment by patrickgold** [comment]
There's currently no way to explicitly do this using only the stylesheet syntax. The only indicator atm is the arrow position and the direction it is pointing to and I cannot quickly change this without forcing this highlight on everyone, so 0.4.0-alpha03 will have this like it is in the latest artifact.

I am however open to fix this issue with my next theme rework sometime in the future. I generally plan to fix some other similar issues and I to allow for more styles based on the state. Not sure how exactly it will be implemented but the base idea is to borrow the `:is()` selector from CSS and use this for these kind of scenarios.

**Comment by KLaurence** [comment]
I wrongly phrased my comment. By "smartbar-action overflow button", I meant the three-dot menu that brings up the menu of additional smartbar-actions (which I also wrongly referred to as the "overflow menu").

However, your comment about styling would still be applicable.

**Comment by patrickgold** [comment]
> I meant the three-dot menu that brings up the menu of additional smartbar-actions

Ah I see I misread it :) Still this button is also not styleable but would also be a candidate for my `:is()` selector solution, I agree here.

**Pull request merged**
