### PR TITLE
Telex Composer for Vietnamese: Add rule for a, ă, ê, ô, ơ, ... [Ticket: #1751 #proposal]

### LINKED ISSUE #1751: Improve Vietnamese keyboard
Support for Telex is welcomed, but it could be better. during normal use on any other keyboard/operating system, you can type the whole word before adding the signs, and they would be centered and be at the correct place. In Floris, you have to type the letters and signs one by one, which is not very convenient.

For example, when I typed "chuoois", the text in the box should be "chuối", not "chuôis", or when I typed "oaf", the returned text should be "òa", not "oà".

Perhaps it's better to learn from iBus' way of implementing Telex on the desktop?

### PR DESCRIPTION
**Pull request by thanhhocse96**
Closes #1751

Add rule for a, ă, ê, ô, ơ,... with the mark tone-mark and modify-mark can type last 
Example: 
"chăm"
+ Before: You only type: "chawm",
+ Now: You can type "chamw",

"làm"
+ Before: "lafm"
+ Now: "lamf"

With every rule for tone-mark, modify-mark, I create the rule to remove the mark
Example:
+ "chămw" => "chamw"
+ "làmf" => "lamf"

Brute force table for checking, I'll update in this wordpress blog: https://wp.me/p9PuPx-119

P/S: (Sorry about my poor English)

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
Could you add "`Closes #1751`" to your first comment? It will
1. Link to the original issue
2. Automatically close the issue when this PR is accepted

**Comment by patrickgold** [comment]
Thanks for your PR, really appreciate it!

As I see, you are working on really extending the Vietnamese keyboard by a lot, thanks for the effort!

I am currently working on majorly reworking the editor caching / input connection logic (prep for the word suggestions to have proper context), when I am done with that I will review and test your PR properly :)

**Comment by patrickgold** [comment]
> In further, I will try make Vietnamese word recommend or auto correct feature.

What do you mean by auto-correct - word suggestions or spell checker?

> I want to ask if you have any document about your code structure and naming convention rule?

No not really and I know that I should have one... Is a mix of me being lazy at this and the project structure having changed over soo much in 0.3.14, 15 and 16. But yeah, maybe I will at least summarize the general structure and naming convention and add this to the contributing guidelines or wiki in the following days.

**Comment by quyleanh** [comment]
@thanhhocse96 thank you very much for your effort.
I will test and give feedback about your brute force table.

It's seems that your florisboard's implementation method is different with IME like Unikey or OpenKey, isn't it?

@patrickgold should we close #931 and #183?

**Comment by cuongpv1991** [comment]
Hi, I really like this key board. However there are still some minor issues like:
quaf > qùa,
neeus > nêú

**Pull request merged**
