### PR TITLE
Create fa3.json

### PR DESCRIPTION
**Pull request by Mahantor**
Add new persian3 layout

### CODE REVIEW

**Comment by tsiflimagas** [comment]
Thanks for your pull request! I think you should have opened only one though, regardless of how many commits you wanted to split the new layout into, since they all have to do with the same specific addition (I think it should have been one commit though, too). Also, it would be helpful to write how it differs from the other Persian layouts.

**Comment by Mahantor** [comment]
Sorry I'm a novice and do not know how to work with GitHub
After making the changes, it seemed to me that I should pull request after each edit to register the changes, but I was wrong
Is there a way to correct these requests ???

**Comment by Mahantor** [comment]
> Thanks for your pull request! I think you should have opened only one though, regardless of how many commits you wanted to split the new layout into, since they all have to do with the same specific addition (I think it should have been one commit though, too). Also, it would be helpful to write how it differs from the other Persian layouts. 

Sorry I'm a novice and do not know how to work with GiteHub
After making the changes, it seemed to me that I should pull request after each edit to register the changes, but I was wrong
Is there a way to correct these requests ???

**Comment by patrickgold** [comment]
@Mahantor I see that you use the `patch-{number}` system. Here on GitHub we do not at all use this, instead we create a feature branch, in this we make all commits for the feature (if necessary also force-push to rewrite the feature-branch history). Please combine your PR into one (with one commit, even though as long as they are in one branch I don't care), so I can properly review it.

I am unsure what's the best approach for you to correct this now, probably by creating a proper feature branch and copy paste your changes in there one-by-one, then making a proper PR with that feature branch. Note that I will close all your 5 PRs to clean up the PR list.

**Pull request closed without merging**
