### PR TITLE
Add Azerbaijani keyboard layout

### PR DESCRIPTION
**Pull request by nijatismayilzada**
Hi,

I am now a fan of this project. Thanks for building this amazing keyboard.

As I am Azerbaijani, I have decided to add Azerbaijani layout support. I have basically copied the Turkish-Q layout, added our beloved "[Ə](https://unicode-table.com/en/0259/)" letter. I also moved the letters around according to the [Azerbaijani Keyboard Layout standard](http://kbdlayout.info/KBDAZEL/).

ISO code AZ: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#AZ

I have tested the changes in Android Studio Virtual Machine with Pixel XL API 31 emulation. All working as expected.

Let me know if there is anything missing or any questions.

### CODE REVIEW

**Comment by patrickgold** [comment]
Sorry for the delay, your PR was made right in the final spurt for the 0.3.14 release, where I was fully focused on fixing bugs and actually making the stable release.

Now the release is done and I can focus again on reviewing PRs :) I just looked through your additions and everything looks fine. I will however still test it locally later, then mergine in your changes.

**Review by patrickgold — CHANGES_REQUESTED** [review]
I just reviewed your changes and your layout looks good.

I would like to request one thing though: Could you please add a subtype preset for Azerbaijani, so it will be available as a suggested subtype in the subtype add screen? Subtype presets are defined here: https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json

Thanks!

**Review by patrickgold — APPROVED** [review]
I added the subtype preset for you, so now the layout is ready for merging

**Comment by nijatismayilzada** [comment]
Oh thanks, @patrickgold, I appreciate your time for reviewing and enhancing this with subtype presets! I am glad this is merged, looking forward to version 0.3.15!

**Pull request merged**
