### PR TITLE
Clipboard shortcut for pinned entries

### LINKED ISSUE #2292: Enable Clipboard shortcut for pinned entries
This feature is supported by clipboard on Microsoft Swiftkeyboard. One can assign single or multiple characters as a shortcut that shows the particular pinned key into suggestion box and pastes the entire content. This is useful as I have several pinned statements (like more than 50) and its easy to manage them.

### PR DESCRIPTION
**Pull request by VishnuSanal**
fixes #2292

### CODE REVIEW

**Comment by lm41** [comment]
Hello what is the state of this pr?

**Comment by VishnuSanal** [comment]
> Hello what is the state of this PR?

hi, I am working on it, will update it soon :)

**Comment by VishnuSanal** [comment]
hi Patrick, thanks for the reivew.

> Unfortunately as I can see I think you misunderstood what issue #2292 requested. however #2292 requested that there is the ability added to add shortcuts to pinned clipboard items in the history, which the word suggestion algorithm then picks up and suggests.

uh, oh! my bad.

> It is up to you if you want to add this but be warned that it is probably a lot more effort due to having to change some behavior across the app and also modify the database structure.

that's alright, I will work on it provided this is a feature that florisboard is okay accepting!

also, what do you think about having this feature as is -- i.e, suggesting the primary clip?

**Comment by patrickgold** [comment]
> also, what do you think about having this feature as is -- i.e, suggesting the primary clip?

That's already an existing feature (Typing > Suggestions group > Clipboard content suggestions)

> that's alright, I will work on it provided this is a feature that florisboard is okay accepting!

generally yeah however thinking about the fact that the work on word suggestions has already started it is probably best if you await that word suggestions itself are implemented before adding features ontop of that code, else we will have unnecessary merge conflicts no one wants

**Comment by VishnuSanal** [comment]
> the work on word suggestions has already started it is probably best if you await that word suggestions itself are implemented before adding features on top of that code, else we will have unnecessary merge conflicts no one wants

alright, please link me to that issue, I will keep an eye. or tag me once it gets completed. closing this PR for now. :)

**Pull request closed without merging**
