### PR TITLE
Clean up codebase

### LINKED ISSUE #330: Codebase Improvements
I have some general suggestions (that I'm willing to put into practice via PRs) for improving FlorisBoard's codebase. These include:
- Cleaning up existing dependencies (some deps are unnecessary, for example, such as stdlib-jre7)
- Using kotlinx-serialization instead of moshi (smaller runtime size, slightly faster, and no reliance on reflection)
- Using Kotlin Gradle build scripts rather than Groovy build scripts and cleaning up build logic
- Storing source files at source root rather than within single-nested subpackages (i.e. `src/main/kotlin/App.kt` rather than `src/main/java/dev/patrickgold/florisboard/App.kt`)

This list isn't exhaustive-- there are other things that could be done too. As these are rather major changes, I wanted to seek approval first.

### PR DESCRIPTION
**Pull request by serebit**
Resolves #330. The following changes have been made:
- Clean up comments in gradle.properties and increase the max heap size for build to 2 GB
- Update the Gradle wrapper to the latest stable version, v6.8.2
- Replace `.gradle` files with their `.gradle.kts` equivalents
- Remove unused `app/.gitignore` and `app/proguard-rules.pro` files
- Add plugin to fetch new dependency versions (run with `gradle dependencyUpdates` or `gradle dU`)
- Update all dependencies and plugins to latest versions (no code changes required)
- Remove unused plugin (kotlin-android-extensions) and unused dependencies
- Build is no longer aborted on lint errors
- Fix build warning concerning unused variables
- Add a standard `.editorconfig` file
- Optimize imports in source files

### CODE REVIEW

**Comment by serebit** [comment]
Due to their scope, `kotlinx-serialization` and `kotlin.Result` will be separate PRs, as will any code cleanup/formatting changes.

**Comment by patrickgold** [comment]
Thanks a lot for your improvements, I really appreciate it! I've had a quick look at them and you definitely have improved quite a bit of the codebase :) I will test your changes out later on my local setup and if everything checks out (what I am pretty sure it will), I will merge your PR into master!

**Comment by patrickgold** [comment]
Thanks again for your changes! I've reviewed them locally and everything builds fine on my setup. Also thanks for running an import statement cleanup, it seems I had quite a few unused imports in my code 😄 

Merging your changes into master now. Note that your changes in `EditorInstance.kt` will get overridden by my suggestions branch once I merge that, as pretty much everything in that file has changed, else your changes should™ be compatible with my suggestions branch.

**Comment by serebit** [comment]
@patrickgold 

> Also thanks for running an import statement cleanup, it seems I had quite a few unused imports in my code :smile: 

No problem! FYI, if you're using Android Studio, there's an IDE feature that'll automatically clean up your import statements; you just have to enable it. More stuff coming after the suggestions branch merge :)

**Comment by patrickgold** [comment]
> No problem! FYI, if you're using Android Studio, there's an IDE feature that'll automatically clean up your import statements; you just have to enable it. More stuff coming after the suggestions branch merge :)

I know that Android Studio has an import cleaner, though automatic cleaning is a TIL for me. Thanks for the tip!

**Pull request merged**
