### PR TITLE
fix upper and lower characters for "i" and "ı"

### PR DESCRIPTION
**Pull request by demirdegerli**
see issue #1840

### CODE REVIEW

**Comment by patrickgold** [comment]
Thanks for your PR!

I think you misunderstood the issue: the issue was that the base character did show a capital I with dot above, however a normal I was written. As such I created a new PR for this issue: #1967 and I think this PR is obsolete. Please also see #1840.

**Comment by demirdegerli** [comment]
correct pr is #1967

**Comment by patrickgold** [comment]
@demirdegerli Is your device language by chance Turkish? If so it explains why the base char issue is not apparent at first, because then every i gets capitalized to İ and it seems correct.

> Here is the capital and lower versions of both letters:

I agree that these are the correct capitalization rules for the i and ı, however those are already implemented correctly (using #1967 as the code base for this statement), or am I mistaken here?

See implementation of the popups for the i and ı: https://github.com/florisboard/florisboard/blob/b576cafaa4a66b128bdb558e5916482c697d3c4e/app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/tr.json#L9-L20

**Comment by demirdegerli** [comment]
Ok, my device language is Turkish and in the QWERTY layout the capital i character "I" showing up "İ" to me because the capitalize method capitalizes the letter for my language. Now I understood, right?

**Comment by demirdegerli** [comment]
@patrickgold Ok, my device language is Turkish and in the QWERTY layout the capital i character "I" showing up "İ" to me because the capitalize method capitalizes the letter for my language. Now I understood, right?

**Comment by patrickgold** [comment]
> Ok, my device language is Turkish and in the QWERTY layout the capital i character "I" showing up "İ" to me because the capitalize method capitalizes the letter for my language. Now I understood, right?

Yup :)

> And with your PR, Turkish users also can use the QWERTY layout?

Yes, with my #1967 fix Turkish users can use QWERTY for both Turkish and English and it will properly adapt thanks to `state.recomputeIfNecessary(evaluator.activeSubtype().primaryLocale)`, for English it is i->I and for Turkish i->İ. Of course there are also the Turkish-Q and Turkish-F layouts, which already have a custom config and should work flawlessly.

**Comment by demirdegerli** [comment]
Ok, thanks!

**Pull request closed without merging**
