### PR TITLE
Vietnamese Telex: Add mising case 

### LINKED ISSUE #1841: [Feedback] Telex Composer for Vietnamese
#### Description
Feedback for Telex Composer for Vietnamese keyboard implemented in #1797 
Since @thanhhocse96 use the brute force table for checking, there will be some cases which is not considered. I will try to test and list up in this issue.

#### List of missing cases

* Normal mark tone
Oiư --> Ơi
Phucs --> Phúc
Phưcs --> Phức
Did --> Đi
Đưcs --> Đức
Vọư --> Vợ
Đêù --> Đều
Lucs --> Lúc
Qúa --> Quá

* Change the tone
Sàngs --> Sáng
Hỏì --> Hòi
Hảf --> Hà

### PR DESCRIPTION
**Pull request by thanhhocse96**
Closes #1841
Add to improve missing case mention in #1841: ic, uc, oc, uôc

Another feature is mentioned in #1841:
+ Change tone-mark: "ungs" => "úng" => "úngf" => "ùng"; "hoio" => "hôi" => "hôiư" => "hơi"
This feature will be in discussion

### CODE REVIEW

**Comment by patrickgold** [comment]
Thanks for your PR and hard work, really appreciate it!

I tested the changes locally and everything checks out as far as I can test it with the given examples. IMO #183 can now also be closed as completed, or do you think something of that issue is still open for implementation?

As for the Git branch itself: Please do never reuse an already merged branch, as you can see above, you pulled the commit history + numerous master merge commits into a completely new PR, which is not intended. Always sync your fork to the latest upstream master and then do `git checkout -b <branch_name>`, so you have a clean working state. In this PR I will just do a squash merge, so not too much trouble, but I just wanted to let you know for the future :)

**Comment by thanhhocse96** [comment]
> Thanks for your PR and hard work, really appreciate it!
> 
> I tested the changes locally and everything checks out as far as I can test it with the given examples. IMO #183 can now also be closed as completed, or do you think something of that issue is still open for implementation?
> 
> As for the Git branch itself: Please do never reuse an already merged branch, as you can see above, you pulled the commit history + numerous master merge commits into a completely new PR, which is not intended. Always sync your fork to the latest upstream master and then do `git checkout -b <branch_name>`, so you have a clean working state. In this PR I will just do a squash merge, so not too much trouble, but I just wanted to let you know for the future :)

Sorry, I just comeback to be developer recently, so sorry about this messed PR

About this feature:
> Change tone-mark: "ungs" => "úng" => "úngf" => "ùng"; "hoio" => "hôi" => "hôiư" => "hơi"
I will look at some approach made by some apps develop by Vietnamese and consider about pros and cons to change the initial approach or I just create some Python script to brute-force all cases and add to the extension.json in the future PR. At the moment this PR just add missing case I missed when bruteforce

**Comment by patrickgold** [comment]
> Sorry, I just comeback to be developer recently, so sorry about this messed PR

Like I said no worries, just wanted to mention it in case you were new to PRs and did not know about it :)

> I will look at some approach made by some apps develop by Vietnamese and consider about pros and cons to change the initial approach or I just create some Python script to brute-force all cases and add to the extension.json in the future PR. At the moment this PR just add missing case I missed when bruteforce

Ok in this case I will squash merge this PR into master then, additional changes can always be provided in a separate PR. Thanks again for your work!

**Comment by Nothing9x** [comment]
It's still missing too many cases of Vietnamese typing rule. I think that you use extension.json file is not the correct way to implement Vietnamese Telex rule

**Pull request merged**
