### PR TITLE
Fix uppercase Greek vowels popups

### LINKED ISSUE #1981: Broken uppercase accented characters in Greek layout
#### Short description
I just came to notice that popups for vowels in Greek don't have any accents, in current HEAD. The offending commit seems to be https://github.com/florisboard/florisboard/commit/b04f8d75f36659beb046fe7ab55d1a8ae1600d4c.
Btw I'm not sure if this should be labeled as `kbd-logic` instead.

#### Steps to reproduce
1. Go to the keyboard, using the Greek layout
2. Hold on a vowel
3. See that popups don't have accents

#### Environment information
- FlorisBoard Version: 0.4.0-alpha01
- Install Source: locally compiled
- Device: Xiaomi Redmi note 8
- Android: Android 12.1, custom rom

### PR DESCRIPTION
**Pull request by tsiflimagas**
So, I gave this a shot, but it turned out I didn't know how to handle more than one popup with `case_selector`. Thus, I'm once again looking for an advice😁

Closes #1981

### CODE REVIEW

**Comment by patrickgold** [comment]
You can put case selectors in the relevant section too, basically you can put a case selector in every spot there an auto text key also fits :)

**Comment by tsiflimagas** [comment]
Thanks, it now works fine! I initially tried some weird stuff and didn't think of the simplest.
One last thing which I just came to notice. It seems like I found out why Gboard doesn't insert `Ϊ́` and `Ϋ́` but only their lowercase forms. These characters don't actually exist standalone in Unicode, instead they're a combination of the plain letter+dieresis+accent. Till now in FlorisBoard I had been using the correct label, but the code was actually just the plain letter. What's weird is that they handle this in AOSP keyboard, but not in Gboard. Anyway, is there any way at the moment to have a combination of letters in the layout, or should I go with what Gboard does with those two characters?

**Comment by patrickgold** [comment]
> Anyway, is there any way at the moment to have a combination of letters in the layout, or should I go with what Gboard does with those two characters?

You can use a [`MultiTextKey`](https://github.com/florisboard/florisboard/blob/79d9e73608c76ed7645e4830caf7e33e78052358/app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt#L557-L565) for this. Actually this would be the first proper use for it. Example (code points are exemplar, you need to insert the correct ones which compose the letter):

```json
{ "$": "multi_text_key", "codePoints": [1, 2, 3], "label": "Ϋ́" }
```

Note that multi text keys do not have an auto case mapper, so you need to use a case selector and put above snippet in for the `upper` variation.

**Comment by tsiflimagas** [comment]
Oh, great! I tried but it seems I'm doing something wrong, as it just outputs the letter without the other two characters, so I pushed it in order for you to spot the mistake easier. I can't quite spot it myself.

**Comment by patrickgold** [comment]
> I tried but it seems I'm doing something wrong, as it just outputs the letter without the other two characters

You are doing everything correct, the issue is that the editor instance and the composer don't support multiple code points... I now adjusted the logic and created PR #1989 to fix this circumstance. I tested the behavior and it inserted the `Ϋ́` as intended for me. If you want you can test this out locally (check out my PR's branch and manually apply the commit you pushed above).

I still need to do some testing if I didn't break something else with this change in the composer, but I am too tired for it now so I will do this tomorrow, then I will merge in the change into master.

**Comment by patrickgold** [comment]
#1984 is now merged, so if you rebase your branch onto the latest master it should work flawlessly now.

**Comment by tsiflimagas** [comment]
Yes, it works great! Thank you 😁

**Review by patrickgold — COMMENTED** [review]
Thanks for the rebase! I did check the changes again and they look good, all the Greek popups are now properly capitalized and inserted correctly.

One question though: For letters with only one popup (`α`, `ε`, `η`, `ο` and `ω`) they previously only had a `relevant` popup, now they have a `main` popup. Is this change intended?

**Comment by tsiflimagas** [comment]
> Is this change intended?

Lol, I actually don't know why I did that, nor noticed there was no reason to. Changed it back.

**Review by patrickgold — APPROVED** [review]
Thanks for the fix, now everything checks out fine. Will merge in the changes now.

**Pull request merged**
