### PR TITLE
Added Hebrew layout

### PR DESCRIPTION
**Pull request by antonygggg**
Added Hebrew layout

### CODE REVIEW

**Comment by patrickgold** [comment]
Thanks for your PR, I really appreciate it!

I've reviewed your changes and I think I have to correct some incorrect brackets. Besides from it, everything should be ok. I will squash your commits to one (so the commit history is clean) and then merge your PR.

**Comment by patrickgold** [comment]
Above commit fixes the language code (Android weirdly uses the old "iw" code rather than "he" for Hebrew). Additionally, I fixed some indentation issue. Squash merging your changes now. Thanks again for your contribution!

**Comment by antonygggg** [comment]
Great thanks

**Comment by antonygggg** [comment]
@patrickgold Just to be sure, in the iw.json file is the name doesn't also need to be iw ? now it is he

https://github.com/florisboard/florisboard/blob/766c5efa95ec8f0f78843417f952eb3128961006/app/src/main/assets/ime/text/characters/extended_popups/iw.json#L3

**Comment by patrickgold** [comment]
@antonygggg Thanks for spotting this! While it technically still works (I successfully tested your layout before merging), this should definitely be corrected. Either you make a patch PR for this quick fix or I just do a quick fix commit, just let me know!

**Comment by antonygggg** [comment]
@antonygggg You can do this. Thank you !

**Comment by patrickgold** [comment]
@antonygggg k thanks for letting me know!

**Pull request merged**
