### PR TITLE
Fix left and right arrow in clipboard cursor row

### PR DESCRIPTION
**Pull request by yashx**
## Before

https://user-images.githubusercontent.com/20506602/103139783-c6c2dd00-4705-11eb-8db4-4cf5dc87c851.mp4

## Now

https://user-images.githubusercontent.com/20506602/103139786-d2ae9f00-4705-11eb-92b6-462e8a41cad7.mp4

### CODE REVIEW

**Comment by RickyM7** [comment]
The same crash reported in #97 occurs here but it has already been fixed in #98.

**Comment by patrickgold** [comment]
@RickyM7 yes this will crash because it uses the old TimerTask, with the #98 solution it will work flawlessly. thanks again for trying it out!

@yashx Thanks for adding this! I just have to think of how to now merge together these changes, as there will definitely be merge conflicts now

**Comment by yashx** [comment]
You can merge #98 first. I will make the appropriate changes in this PR so there are no conflicts.

**Comment by patrickgold** [comment]
@yashx thanks! I will add the fix for EditingKeyView, then merge it into master, so you can adjust this change.

**Comment by yashx** [comment]
@patrickgold I think it can be merged now.

**Comment by patrickgold** [comment]
@yashx I've tested your changes and everything checks out. Thanks again for your contributions!

**Pull request merged**
