### PR TITLE
Adding new layout for Persian

### PR DESCRIPTION
**Pull request by m-koushan**
Simply added new layout based on Swiftkey keyboard Persian layout. New popups too (I don't know it will work or not)

### CODE REVIEW

**Comment by patrickgold** [comment]
Thanks for your PR!

I had to do a bit of cleanup due to multiple master merges into the PR, now cherry-picked the relevant changes and rebased on the current master state. I additionally fixed whitespace issues, your language code (fa-Fa-per2 does not work), and also added the characters mod to the extension.json file.

Tested it out locally and from a non-Persian speaking person everything checks out fine. Could you still please download the artifact APK of this PR to check when typing that the character placement and such is correct within the UI? Thanks!

**Comment by m-koushan** [comment]
Thanks for fixing
I installed the PR artifact APK and i find out the popup for "half-space" key is not showing. I don't know how to fix it but i guess the issue is at `app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/fa2.json` Line 8:
```
...
      "‌": {
...
```
i think putting `half_space` instead of the actual character will fix it. but i'm not totally sure
Also i forgot to change the line 79 of the fa2.json file
pls remove the line 84 first (`{ "code": 1567, "label": "؟"}`) 
and change the line 79 to this: 
`"main": { "code": 1567, "label": "؟" },`
thanks again.

**Comment by patrickgold** [comment]
> i think putting half_space instead of the actual character will fix it

Yes putting `half_space` fixed the popups.

I also changed the lines 79 and 84 according to your instructions, everything should now be ok. Will merge in the changes now, thanks for your work!

Just a heads up: in your original `Adding new layout Persian2` commit you used an email address which has not been added to your GitHub account (a Gmail one). If you add it in the account's email options, you will be listed as the author, not me as GitHub incorrectly shows it.

**Comment by patrickgold** [comment]
Nevermind in the squash commit GitHub auto-uses your email used in your GitHub account, so no need to add it at all.

**Pull request merged**
