### PR TITLE
Some gesture typing enhancements

### LINKED ISSUE #593: Florisboard crashing trying to choose a design
Hi,
I can reproduce this error anytime with following setup:
Android 11
FlorisBoard 0.3.10
Xiamoi Mi 9 SE
Steps to reproduce:
1.Open Settings 
2. Go to Design
3. either way in light or dark mode click on chosen design.

However i have installed both 0.3.10-beta06 & 0.3.10 and this bug only occurs when 0.3.10 is NOT activated in android keyboard settings.
When keyboard is activated this error does not happen.
This does not happen with 0.3.10-beta06
~~~ 1617951622746.stacktrace ~~~

java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.patrickgold.florisboard/dev.patrickgold.florisboard.settings.ThemeManagerActivity}: android.view.InflateException: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Error inflating class dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.InflateException: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Error inflating class dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView
Caused by: android.view.InflateException: Binary XML file line #37 in dev.patrickgold.florisboard:layout/theme_manager_activity: Error inflating class dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at dev.patrickgold.florisboard.databinding.ThemeManagerActivityBinding.inflate(ThemeManagerActivityBinding.java:101)
	at dev.patrickgold.florisboard.databinding.ThemeManagerActivityBinding.inflate(ThemeManagerActivityBinding.java:95)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.onCreateBinding(ThemeManagerActivity.kt:159)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.onCreateBinding(ThemeManagerActivity.kt:52)
	at dev.patrickgold.florisboard.ime.core.FlorisActivity.onCreate(FlorisActivity.kt:52)
	at dev.patrickgold.florisboard.settings.ThemeManagerActivity.onCreate(ThemeManagerActivity.kt:124)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.FlorisBoard$Companion.getInstance(FlorisBoard.kt:182)
	at dev.patrickgold.florisboard.ime.text.gestures.GlideTypingManager$Companion.getInstance(GlideTypingManager.kt:32)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:80)
	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.<init>(KeyboardView.kt:88)
	... 38 more

### PR DESCRIPTION
**Pull request by X-yl**
Hey, just a few tweaks to the gesture typing thing. 

Changelog:

* Make the distance threshold dynamic (1/4 of key width, was previously statically set to 1000)
* Gestures without repeating letters only have one ideal gesture instead of two duplicates (should give a little performance boost)
* Android batches move events, and I forgot to process all the batched events as well (could be important if android batches a lot of events together, like if CPU is limited or something)
* I was setting the wrong time for the glide suggestions which caused them to (sometimes) appear in the wrong order 
* Should have fixed #593 
* Made the glide trail length customizable
* Cache word data instead of loading it from the json every time
* Added a few rules for #616 and #596, I made it so that no space for symbols was default and then added exceptions for some characters. More rules probably do need to be added
* Also I ran the auto format so that's why the diff is a bit bloated

Let me know if you want any changes.

### CODE REVIEW

**Comment by patrickgold** [comment]
Thanks for your PR, really appreciate it! I've tested out the changes locally and could not find an issue regarding the changelog. Also the crash for the theme settings UI is now fixed, thanks for that!

As for the symbols-with-space json file: for now we can leave this one in but this will definitely be reworked (either we use a standardized format from a source which provides this rules or we create a better json format). The main issue is that different languages require different rule sets, and we will have to account for that somehow. But thanks nevertheless for adding this temporarily, it is by far better than nothing!

**Comment by tsiflimagas** [comment]
These changes look gorgeous! The only little issue introduced (I don't know if it's actually something expected) is that the trail now doesn't fade until you release it. So you can create a long trail and keep it drawn by holding your finger. Just a small thing, mostly about consistency of the feature. Neat job!

**Comment by theotheroracle** [comment]
testing out glide feature seems to be getting better

**Comment by theotheroracle** [comment]
yeah the delay doesn't seem to actual affect anythinf

**Pull request merged**
