### PR TITLE
Switch to emulating hardware key press to delete

### LINKED ISSUE #64: Backspace doesn't work with single number inputs
**Environment information**
- FlorisBoard Version: 0.2.6
- Install Source: GitHub
- Device: OnePlus 8T
- Android version, ROM: 10, OxygenOS

**Steps to reproduce**
1. Open an app which uses multiple single number inputs
2. Type some numbers in
3. Try deleting them
4. It only deletes from the currently active input

During the setup of my new phone a noticed this bug in Telegram. I don't know if it's really a bug or just not implemented.
I still have Gapps right now so I can confirm this is not a bug within Telegram.

<details><summary>Screen Recording</summary>
<p>

untitled

</p>
</details>

### LINKED ISSUE #86: Deletion doesn't work in some cases
**Environment information**
- FlorisBoard Version: 
- Install Source: F-Droid
- Device: Mi A2
- Android version, ROM: 10, LineageOS

Comparison of AnySoftKeyboard and FlorisBoard with respect to backspace/deletion:
1. Telegram
ScreenRecord-2020-12-16-17-52-53

Sorry, GitHub doesn't support big gif files so I'll just put a public Telegram link to a public channel post with the gif :(
2. uBlock Origin "my filters" editor:
https://t.me/testbuggy/2
3. a CodiMD instance hosted by someone: 
https://t.me/testbuggy/5

### LINKED ISSUE #95: weird deletion cases
Below is an experiment conducted on the uBlock Origin (installed on firefox android) element selector text input field. AnySoftKeyboard deletes only the characters on the left of the cursor, always, as you keep the backspace pressed. FlorisBoard somehow deletes characters on both sides as you repeat the same backspace long press action.
Experiment:
https://gifyu.com/image/CuH8
(sorry, github doesn't allow large gifs)

**Environment information**
- FlorisBoard Version: 3.1.0
- Install Source: F-Droid
- Device: Mi A2
- Android version, ROM: 10, LineageOS

### PR DESCRIPTION
**Pull request by yashx**
I did some basic tests and tried the keyboard in situations discussed in #95 and #64 It works. 

closes #95 closes #64 closes #86

### CODE REVIEW

**Comment by RickyM7** [comment]
+

**Comment by RickyM7** [comment]
In my test the issues #64 and #86 have been fixed but the implementation of the #95 did not work here.
Device: Redmi Note 4 (MIUI 11 - Android 7.0)

**Comment by patrickgold** [comment]
Thanks for fixing the delete key behavior, I really appreciate it!

I've done a quick test and it works fine. Still I want to test it with my usual suspects later (either later this evening or tomorrow), to ensure this new method still works fine with them. I've had my experiences with some apps before, where they just ghost FlorisBard after sending a hardware emulated key like `KEYCODE_DELETE`, until the input connection is rebuilt.

**Comment by patrickgold** [comment]
@RickyM7 Oh no your case is the Firefox Fenix thing agghh... Sometimes I hate the input editor implementation of Firefox, where it just ignores FlorisBoard, and thus the input is completely messed up, as shown by your screen recording in #95. I will look into it, probably tomorrow.

**Comment by RickyM7** [comment]
@patrickgold Actually it wasn't me who opened the issue #95 and I also do not use Firefox Fenix. I tested this on other apps but it wasn't fixed.

**Comment by patrickgold** [comment]
@RickyM7 Now that you say it yeah you are right but still, I had my troubles with Firefix Fenix in the past and when FlorisBoard breaks then it is most probably in a browser input field of Firefox (or in this case uBlock Origin on any browser). I've just tried the uBlock Origin input with the emulated hardware on Firefox Fenix and it was better than the screen recording but still did some weird jumps while holding the delete key.

**Comment by yashx** [comment]
Weird, on my phone #95 is fixed

https://user-images.githubusercontent.com/20506602/103141929-e8ca5880-4721-11eb-9c9d-3e3cdaf03c7f.mp4

**Comment by RickyM7** [comment]
@patrickgold Got it! Anyway I will test as soon as possible the next debug builds that come out and i will give my feedback.

**Comment by patrickgold** [comment]
@yashx I currently have to do something else, when I've time again I will make a screen recording of my Firefox Fenix browser with the uBlock Origin behavior.

**Comment by patrickgold** [comment]
@RickyM7 Thanks for testing out nearly every debug build today and being so helpful, I really appreciate this! :)

**Comment by yashx** [comment]
It's like 2:30 am here. I can't sleep so I am just messing around. I will probably open a few more PR so review them when you have the time. No hurry.

**Comment by patrickgold** [comment]
@yashx Ok I've played around with the uBlock Origin filter input field for a while now and found out that this input field itself is very buggy, to say the least. Also the behavior differs from Gboard to OpenBoard to FlorisBoard. There are cases where FlorisBoard worked flawlessly while Gboard did some super weird stuff. Then vice versa.... it depends which CSS rules are existent it seems to me. IMO this input field should not be accounted whether this improvement works or not.

What I can for certain say though is that the hardware emulation key delete works flawlessly in every other Firefox Fenix input field, which is a good sign that this implementation really works. Also in every other app on my testing rig there were no crashes or other bugs, which is great!

I will merge this PR sometime tomorrow after having confirmed with Ricky that his case is fixed too.

@RickyM7 As you said that #95 isn't fixed for you, may I ask in which app(s) / input field(s) the delete key was still bugged for you?

**Comment by RickyM7** [comment]
@patrickgold I just tested properly (on uBlock in Firefox Fenix) and the #95 has been fixed. I'm sorry about that, but I confused the buggy behavior with the expected behavior, I think. On my phone the text is deleted only from the cursor position (as in the screenrecord of the @yashx), this is the expected behavior, right?

**Comment by yashx** [comment]
Yes, in #95 the gif was showing that only AnySoft keyboard was able to delete properly in Firefox.
Both AOSP and Floris keyboard was having issues as instead of only deleting characters on the left  of cursor when backspace was pressed it also deleted characters on right.

**Comment by patrickgold** [comment]
@RickyM7 cool, thanks for clarifying and the help!

@yashx Thanks again for improving the key deletion behavior!

I will now merge this change into master, as I see no reason to hold it back any longer.

**Pull request merged**
